
package com.microsoft.schemas.sharepoint.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AlertsSoap", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlertsSoap {


    /**
     * 
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.AlertInfo
     */
    @WebMethod(operationName = "GetAlerts", action = "http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/GetAlerts")
    @WebResult(name = "GetAlertsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/")
    @RequestWrapper(localName = "GetAlerts", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/", className = "com.microsoft.schemas.sharepoint.soap.GetAlerts")
    @ResponseWrapper(localName = "GetAlertsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/", className = "com.microsoft.schemas.sharepoint.soap.GetAlertsResponse")
    public AlertInfo getAlerts();

    /**
     * 
     * @param iDs
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.ArrayOfDeleteFailure
     */
    @WebMethod(operationName = "DeleteAlerts", action = "http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/DeleteAlerts")
    @WebResult(name = "DeleteAlertsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/")
    @RequestWrapper(localName = "DeleteAlerts", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/", className = "com.microsoft.schemas.sharepoint.soap.DeleteAlerts")
    @ResponseWrapper(localName = "DeleteAlertsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/", className = "com.microsoft.schemas.sharepoint.soap.DeleteAlertsResponse")
    public ArrayOfDeleteFailure deleteAlerts(
        @WebParam(name = "IDs", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/")
        ArrayOfString iDs);

}
