
package com.microsoft.schemas.sharepoint.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Alerts", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/", wsdlLocation = "file:/C:/Users/matko/Desktop/wsdl/Alerts.wsdl")
public class Alerts
    extends Service
{

    private final static URL ALERTS_WSDL_LOCATION;
    private final static WebServiceException ALERTS_EXCEPTION;
    private final static QName ALERTS_QNAME = new QName("http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/", "Alerts");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/matko/Desktop/wsdl/Alerts.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALERTS_WSDL_LOCATION = url;
        ALERTS_EXCEPTION = e;
    }

    public Alerts() {
        super(__getWsdlLocation(), ALERTS_QNAME);
    }

    public Alerts(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALERTS_QNAME, features);
    }

    public Alerts(URL wsdlLocation) {
        super(wsdlLocation, ALERTS_QNAME);
    }

    public Alerts(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALERTS_QNAME, features);
    }

    public Alerts(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Alerts(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AlertsSoap
     */
    @WebEndpoint(name = "AlertsSoap")
    public AlertsSoap getAlertsSoap() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/", "AlertsSoap"), AlertsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlertsSoap
     */
    @WebEndpoint(name = "AlertsSoap")
    public AlertsSoap getAlertsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/", "AlertsSoap"), AlertsSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns AlertsSoap
     */
    @WebEndpoint(name = "AlertsSoap12")
    public AlertsSoap getAlertsSoap12() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/", "AlertsSoap12"), AlertsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlertsSoap
     */
    @WebEndpoint(name = "AlertsSoap12")
    public AlertsSoap getAlertsSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/", "AlertsSoap12"), AlertsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALERTS_EXCEPTION!= null) {
            throw ALERTS_EXCEPTION;
        }
        return ALERTS_WSDL_LOCATION;
    }

}
