
package com.microsoft.schemas.sharepoint.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Copy", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", wsdlLocation = "file:/C:/Users/matko/Desktop/wsdl/copy.wsdl")
public class Copy
    extends Service
{

    private final static URL COPY_WSDL_LOCATION;
    private final static WebServiceException COPY_EXCEPTION;
    private final static QName COPY_QNAME = new QName("http://schemas.microsoft.com/sharepoint/soap/", "Copy");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/matko/Desktop/wsdl/copy.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COPY_WSDL_LOCATION = url;
        COPY_EXCEPTION = e;
    }

    public Copy() {
        super(__getWsdlLocation(), COPY_QNAME);
    }

    public Copy(WebServiceFeature... features) {
        super(__getWsdlLocation(), COPY_QNAME, features);
    }

    public Copy(URL wsdlLocation) {
        super(wsdlLocation, COPY_QNAME);
    }

    public Copy(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COPY_QNAME, features);
    }

    public Copy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Copy(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CopySoap
     */
    @WebEndpoint(name = "CopySoap")
    public CopySoap getCopySoap() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "CopySoap"), CopySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CopySoap
     */
    @WebEndpoint(name = "CopySoap")
    public CopySoap getCopySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "CopySoap"), CopySoap.class, features);
    }

    /**
     * 
     * @return
     *     returns CopySoap
     */
    @WebEndpoint(name = "CopySoap12")
    public CopySoap getCopySoap12() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "CopySoap12"), CopySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CopySoap
     */
    @WebEndpoint(name = "CopySoap12")
    public CopySoap getCopySoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "CopySoap12"), CopySoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COPY_EXCEPTION!= null) {
            throw COPY_EXCEPTION;
        }
        return COPY_WSDL_LOCATION;
    }

}
