
package com.microsoft.schemas.sharepoint.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Dws", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/dws/", wsdlLocation = "file:/C:/Users/matko/Desktop/wsdl/dws.wsdl")
public class Dws
    extends Service
{

    private final static URL DWS_WSDL_LOCATION;
    private final static WebServiceException DWS_EXCEPTION;
    private final static QName DWS_QNAME = new QName("http://schemas.microsoft.com/sharepoint/soap/dws/", "Dws");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/matko/Desktop/wsdl/dws.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DWS_WSDL_LOCATION = url;
        DWS_EXCEPTION = e;
    }

    public Dws() {
        super(__getWsdlLocation(), DWS_QNAME);
    }

    public Dws(WebServiceFeature... features) {
        super(__getWsdlLocation(), DWS_QNAME, features);
    }

    public Dws(URL wsdlLocation) {
        super(wsdlLocation, DWS_QNAME);
    }

    public Dws(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DWS_QNAME, features);
    }

    public Dws(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Dws(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DwsSoap
     */
    @WebEndpoint(name = "DwsSoap")
    public DwsSoap getDwsSoap() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/dws/", "DwsSoap"), DwsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DwsSoap
     */
    @WebEndpoint(name = "DwsSoap")
    public DwsSoap getDwsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/dws/", "DwsSoap"), DwsSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns DwsSoap
     */
    @WebEndpoint(name = "DwsSoap12")
    public DwsSoap getDwsSoap12() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/dws/", "DwsSoap12"), DwsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DwsSoap
     */
    @WebEndpoint(name = "DwsSoap12")
    public DwsSoap getDwsSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/dws/", "DwsSoap12"), DwsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DWS_EXCEPTION!= null) {
            throw DWS_EXCEPTION;
        }
        return DWS_WSDL_LOCATION;
    }

}
