
package com.microsoft.schemas.sharepoint.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FormsSoap", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FormsSoap {


    /**
     * 
     * @param listName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetFormCollectionResponse.GetFormCollectionResult
     */
    @WebMethod(operationName = "GetFormCollection", action = "http://schemas.microsoft.com/sharepoint/soap/GetFormCollection")
    @WebResult(name = "GetFormCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetFormCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetFormCollection")
    @ResponseWrapper(localName = "GetFormCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetFormCollectionResponse")
    public com.microsoft.schemas.sharepoint.soap.GetFormCollectionResponse.GetFormCollectionResult getFormCollection(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName);

    /**
     * 
     * @param listName
     * @param formUrl
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetFormResponse.GetFormResult
     */
    @WebMethod(operationName = "GetForm", action = "http://schemas.microsoft.com/sharepoint/soap/GetForm")
    @WebResult(name = "GetFormResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetForm", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetForm")
    @ResponseWrapper(localName = "GetFormResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetFormResponse")
    public com.microsoft.schemas.sharepoint.soap.GetFormResponse.GetFormResult getForm(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "formUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String formUrl);

}
