
package com.microsoft.schemas.sharepoint.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Forms", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", wsdlLocation = "file:/C:/Users/matko/Desktop/wsdl/forms.wsdl")
public class Forms
    extends Service
{

    private final static URL FORMS_WSDL_LOCATION;
    private final static WebServiceException FORMS_EXCEPTION;
    private final static QName FORMS_QNAME = new QName("http://schemas.microsoft.com/sharepoint/soap/", "Forms");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/matko/Desktop/wsdl/forms.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FORMS_WSDL_LOCATION = url;
        FORMS_EXCEPTION = e;
    }

    public Forms() {
        super(__getWsdlLocation(), FORMS_QNAME);
    }

    public Forms(WebServiceFeature... features) {
        super(__getWsdlLocation(), FORMS_QNAME, features);
    }

    public Forms(URL wsdlLocation) {
        super(wsdlLocation, FORMS_QNAME);
    }

    public Forms(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FORMS_QNAME, features);
    }

    public Forms(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Forms(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FormsSoap
     */
    @WebEndpoint(name = "FormsSoap")
    public FormsSoap getFormsSoap() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "FormsSoap"), FormsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FormsSoap
     */
    @WebEndpoint(name = "FormsSoap")
    public FormsSoap getFormsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "FormsSoap"), FormsSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns FormsSoap
     */
    @WebEndpoint(name = "FormsSoap12")
    public FormsSoap getFormsSoap12() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "FormsSoap12"), FormsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FormsSoap
     */
    @WebEndpoint(name = "FormsSoap12")
    public FormsSoap getFormsSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "FormsSoap12"), FormsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FORMS_EXCEPTION!= null) {
            throw FORMS_EXCEPTION;
        }
        return FORMS_WSDL_LOCATION;
    }

}
