
package com.microsoft.schemas.sharepoint.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImagingSoap", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImagingSoap {


    /**
     * 
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.ListPictureLibraryResponse.ListPictureLibraryResult
     */
    @WebMethod(operationName = "ListPictureLibrary", action = "http://schemas.microsoft.com/sharepoint/soap/ois/ListPictureLibrary")
    @WebResult(name = "ListPictureLibraryResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
    @RequestWrapper(localName = "ListPictureLibrary", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.ListPictureLibrary")
    @ResponseWrapper(localName = "ListPictureLibraryResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.ListPictureLibraryResponse")
    public com.microsoft.schemas.sharepoint.soap.ListPictureLibraryResponse.ListPictureLibraryResult listPictureLibrary();

    /**
     * 
     * @param bytes
     * @param strFolder
     * @param fOverWriteIfExist
     * @param fileName
     * @param strListName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.UploadResponse.UploadResult
     */
    @WebMethod(operationName = "Upload", action = "http://schemas.microsoft.com/sharepoint/soap/ois/Upload")
    @WebResult(name = "UploadResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
    @RequestWrapper(localName = "Upload", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.Upload")
    @ResponseWrapper(localName = "UploadResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.UploadResponse")
    public com.microsoft.schemas.sharepoint.soap.UploadResponse.UploadResult upload(
        @WebParam(name = "strListName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strListName,
        @WebParam(name = "strFolder", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strFolder,
        @WebParam(name = "bytes", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        byte[] bytes,
        @WebParam(name = "fileName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String fileName,
        @WebParam(name = "fOverWriteIfExist", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        boolean fOverWriteIfExist);

    /**
     * 
     * @param itemFileNames
     * @param strFolder
     * @param strListName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetItemsXMLDataResponse.GetItemsXMLDataResult
     */
    @WebMethod(operationName = "GetItemsXMLData", action = "http://schemas.microsoft.com/sharepoint/soap/ois/GetItemsXMLData")
    @WebResult(name = "GetItemsXMLDataResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
    @RequestWrapper(localName = "GetItemsXMLData", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.GetItemsXMLData")
    @ResponseWrapper(localName = "GetItemsXMLDataResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.GetItemsXMLDataResponse")
    public com.microsoft.schemas.sharepoint.soap.GetItemsXMLDataResponse.GetItemsXMLDataResult getItemsXMLData(
        @WebParam(name = "strListName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strListName,
        @WebParam(name = "strFolder", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strFolder,
        @WebParam(name = "itemFileNames", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        ArrayOfString itemFileNames);

    /**
     * 
     * @param ids
     * @param strListName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetItemsByIdsResponse.GetItemsByIdsResult
     */
    @WebMethod(operationName = "GetItemsByIds", action = "http://schemas.microsoft.com/sharepoint/soap/ois/GetItemsByIds")
    @WebResult(name = "GetItemsByIdsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
    @RequestWrapper(localName = "GetItemsByIds", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.GetItemsByIds")
    @ResponseWrapper(localName = "GetItemsByIdsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.GetItemsByIdsResponse")
    public com.microsoft.schemas.sharepoint.soap.GetItemsByIdsResponse.GetItemsByIdsResult getItemsByIds(
        @WebParam(name = "strListName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strListName,
        @WebParam(name = "ids", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        ArrayOfUnsignedInt ids);

    /**
     * 
     * @param itemFileNames
     * @param strFolder
     * @param strListName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.DeleteResponse.DeleteResult
     */
    @WebMethod(operationName = "Delete", action = "http://schemas.microsoft.com/sharepoint/soap/ois/Delete")
    @WebResult(name = "DeleteResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.DeleteResponse")
    public com.microsoft.schemas.sharepoint.soap.DeleteResponse.DeleteResult delete(
        @WebParam(name = "strListName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strListName,
        @WebParam(name = "strFolder", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strFolder,
        @WebParam(name = "itemFileNames", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        ArrayOfString itemFileNames);

    /**
     * 
     * @param itemFileNames
     * @param strFolder
     * @param strListName
     * @param type
     * @param fFetchOriginalIfNotAvailable
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.DownloadResponse.DownloadResult
     */
    @WebMethod(operationName = "Download", action = "http://schemas.microsoft.com/sharepoint/soap/ois/Download")
    @WebResult(name = "DownloadResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
    @RequestWrapper(localName = "Download", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.Download")
    @ResponseWrapper(localName = "DownloadResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.DownloadResponse")
    public com.microsoft.schemas.sharepoint.soap.DownloadResponse.DownloadResult download(
        @WebParam(name = "strListName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strListName,
        @WebParam(name = "strFolder", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strFolder,
        @WebParam(name = "itemFileNames", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        ArrayOfString itemFileNames,
        @WebParam(name = "type", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        long type,
        @WebParam(name = "fFetchOriginalIfNotAvailable", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        boolean fFetchOriginalIfNotAvailable);

    /**
     * 
     * @param recipe
     * @param itemFileName
     * @param strFolder
     * @param strListName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.EditResponse.EditResult
     */
    @WebMethod(operationName = "Edit", action = "http://schemas.microsoft.com/sharepoint/soap/ois/Edit")
    @WebResult(name = "EditResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
    @RequestWrapper(localName = "Edit", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.Edit")
    @ResponseWrapper(localName = "EditResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.EditResponse")
    public com.microsoft.schemas.sharepoint.soap.EditResponse.EditResult edit(
        @WebParam(name = "strListName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strListName,
        @WebParam(name = "strFolder", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strFolder,
        @WebParam(name = "itemFileName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String itemFileName,
        @WebParam(name = "recipe", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        com.microsoft.schemas.sharepoint.soap.Edit.Recipe recipe);

    /**
     * 
     * @param strFolder
     * @param strListName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetListItemsResponse.GetListItemsResult
     */
    @WebMethod(operationName = "GetListItems", action = "http://schemas.microsoft.com/sharepoint/soap/ois/GetListItems")
    @WebResult(name = "GetListItemsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
    @RequestWrapper(localName = "GetListItems", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.GetListItems")
    @ResponseWrapper(localName = "GetListItemsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.GetListItemsResponse")
    public com.microsoft.schemas.sharepoint.soap.GetListItemsResponse.GetListItemsResult getListItems(
        @WebParam(name = "strListName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strListName,
        @WebParam(name = "strFolder", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strFolder);

    /**
     * 
     * @param strUrl
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.CheckSubwebAndListResponse.CheckSubwebAndListResult
     */
    @WebMethod(operationName = "CheckSubwebAndList", action = "http://schemas.microsoft.com/sharepoint/soap/ois/CheckSubwebAndList")
    @WebResult(name = "CheckSubwebAndListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
    @RequestWrapper(localName = "CheckSubwebAndList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.CheckSubwebAndList")
    @ResponseWrapper(localName = "CheckSubwebAndListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.CheckSubwebAndListResponse")
    public com.microsoft.schemas.sharepoint.soap.CheckSubwebAndListResponse.CheckSubwebAndListResult checkSubwebAndList(
        @WebParam(name = "strUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strUrl);

    /**
     * 
     * @param strFolder
     * @param request
     * @param strListName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.RenameResponse.RenameResult
     */
    @WebMethod(operationName = "Rename", action = "http://schemas.microsoft.com/sharepoint/soap/ois/Rename")
    @WebResult(name = "RenameResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
    @RequestWrapper(localName = "Rename", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.Rename")
    @ResponseWrapper(localName = "RenameResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.RenameResponse")
    public com.microsoft.schemas.sharepoint.soap.RenameResponse.RenameResult rename(
        @WebParam(name = "strListName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strListName,
        @WebParam(name = "strFolder", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strFolder,
        @WebParam(name = "request", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        com.microsoft.schemas.sharepoint.soap.Rename.Request request);

    /**
     * 
     * @param strListName
     * @param strParentFolder
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.CreateNewFolderResponse.CreateNewFolderResult
     */
    @WebMethod(operationName = "CreateNewFolder", action = "http://schemas.microsoft.com/sharepoint/soap/ois/CreateNewFolder")
    @WebResult(name = "CreateNewFolderResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
    @RequestWrapper(localName = "CreateNewFolder", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.CreateNewFolder")
    @ResponseWrapper(localName = "CreateNewFolderResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", className = "com.microsoft.schemas.sharepoint.soap.CreateNewFolderResponse")
    public com.microsoft.schemas.sharepoint.soap.CreateNewFolderResponse.CreateNewFolderResult createNewFolder(
        @WebParam(name = "strListName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strListName,
        @WebParam(name = "strParentFolder", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/")
        String strParentFolder);

}
