
package com.microsoft.schemas.sharepoint.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Imaging", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/ois/", wsdlLocation = "file:/C:/Users/matko/Desktop/wsdl/imaging.wsdl")
public class Imaging
    extends Service
{

    private final static URL IMAGING_WSDL_LOCATION;
    private final static WebServiceException IMAGING_EXCEPTION;
    private final static QName IMAGING_QNAME = new QName("http://schemas.microsoft.com/sharepoint/soap/ois/", "Imaging");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/matko/Desktop/wsdl/imaging.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMAGING_WSDL_LOCATION = url;
        IMAGING_EXCEPTION = e;
    }

    public Imaging() {
        super(__getWsdlLocation(), IMAGING_QNAME);
    }

    public Imaging(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMAGING_QNAME, features);
    }

    public Imaging(URL wsdlLocation) {
        super(wsdlLocation, IMAGING_QNAME);
    }

    public Imaging(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMAGING_QNAME, features);
    }

    public Imaging(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Imaging(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImagingSoap
     */
    @WebEndpoint(name = "ImagingSoap")
    public ImagingSoap getImagingSoap() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/ois/", "ImagingSoap"), ImagingSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImagingSoap
     */
    @WebEndpoint(name = "ImagingSoap")
    public ImagingSoap getImagingSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/ois/", "ImagingSoap"), ImagingSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ImagingSoap
     */
    @WebEndpoint(name = "ImagingSoap12")
    public ImagingSoap getImagingSoap12() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/ois/", "ImagingSoap12"), ImagingSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImagingSoap
     */
    @WebEndpoint(name = "ImagingSoap12")
    public ImagingSoap getImagingSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/ois/", "ImagingSoap12"), ImagingSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMAGING_EXCEPTION!= null) {
            throw IMAGING_EXCEPTION;
        }
        return IMAGING_WSDL_LOCATION;
    }

}
