
package com.microsoft.schemas.sharepoint.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MeetingsSoap", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MeetingsSoap {


    /**
     * 
     * @param timeZoneInformation
     * @param lcid
     * @param title
     * @param templateName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.CreateWorkspaceResponse.CreateWorkspaceResult
     */
    @WebMethod(operationName = "CreateWorkspace", action = "http://schemas.microsoft.com/sharepoint/soap/meetings/CreateWorkspace")
    @WebResult(name = "CreateWorkspaceResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
    @RequestWrapper(localName = "CreateWorkspace", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.CreateWorkspace")
    @ResponseWrapper(localName = "CreateWorkspaceResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.CreateWorkspaceResponse")
    public com.microsoft.schemas.sharepoint.soap.CreateWorkspaceResponse.CreateWorkspaceResult createWorkspace(
        @WebParam(name = "title", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String title,
        @WebParam(name = "templateName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String templateName,
        @WebParam(name = "lcid", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        long lcid,
        @WebParam(name = "timeZoneInformation", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        TimeZoneInf timeZoneInformation);

    /**
     * 
     */
    @WebMethod(operationName = "DeleteWorkspace", action = "http://schemas.microsoft.com/sharepoint/soap/meetings/DeleteWorkspace")
    @RequestWrapper(localName = "DeleteWorkspace", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.DeleteWorkspace")
    @ResponseWrapper(localName = "DeleteWorkspaceResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.DeleteWorkspaceResponse")
    public void deleteWorkspace();

    /**
     * 
     * @param recurring
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetMeetingWorkspacesResponse.GetMeetingWorkspacesResult
     */
    @WebMethod(operationName = "GetMeetingWorkspaces", action = "http://schemas.microsoft.com/sharepoint/soap/meetings/GetMeetingWorkspaces")
    @WebResult(name = "GetMeetingWorkspacesResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
    @RequestWrapper(localName = "GetMeetingWorkspaces", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.GetMeetingWorkspaces")
    @ResponseWrapper(localName = "GetMeetingWorkspacesResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.GetMeetingWorkspacesResponse")
    public com.microsoft.schemas.sharepoint.soap.GetMeetingWorkspacesResponse.GetMeetingWorkspacesResult getMeetingWorkspaces(
        @WebParam(name = "recurring", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        boolean recurring);

    /**
     * 
     * @param title
     */
    @WebMethod(operationName = "SetWorkspaceTitle", action = "http://schemas.microsoft.com/sharepoint/soap/meetings/SetWorkspaceTitle")
    @RequestWrapper(localName = "SetWorkspaceTitle", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.SetWorkspaceTitle")
    @ResponseWrapper(localName = "SetWorkspaceTitleResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.SetWorkspaceTitleResponse")
    public void setWorkspaceTitle(
        @WebParam(name = "title", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String title);

    /**
     * 
     * @param icalText
     * @param organizerEmail
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.AddMeetingFromICalResponse.AddMeetingFromICalResult
     */
    @WebMethod(operationName = "AddMeetingFromICal", action = "http://schemas.microsoft.com/sharepoint/soap/meetings/AddMeetingFromICal")
    @WebResult(name = "AddMeetingFromICalResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
    @RequestWrapper(localName = "AddMeetingFromICal", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.AddMeetingFromICal")
    @ResponseWrapper(localName = "AddMeetingFromICalResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.AddMeetingFromICalResponse")
    public com.microsoft.schemas.sharepoint.soap.AddMeetingFromICalResponse.AddMeetingFromICalResult addMeetingFromICal(
        @WebParam(name = "organizerEmail", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String organizerEmail,
        @WebParam(name = "icalText", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String icalText);

    /**
     * 
     * @param uid
     * @param title
     * @param utcDateStamp
     * @param location
     * @param sequence
     * @param utcDateEnd
     * @param nonGregorian
     * @param organizerEmail
     * @param utcDateStart
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.AddMeetingResponse.AddMeetingResult
     */
    @WebMethod(operationName = "AddMeeting", action = "http://schemas.microsoft.com/sharepoint/soap/meetings/AddMeeting")
    @WebResult(name = "AddMeetingResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
    @RequestWrapper(localName = "AddMeeting", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.AddMeeting")
    @ResponseWrapper(localName = "AddMeetingResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.AddMeetingResponse")
    public com.microsoft.schemas.sharepoint.soap.AddMeetingResponse.AddMeetingResult addMeeting(
        @WebParam(name = "organizerEmail", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String organizerEmail,
        @WebParam(name = "uid", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String uid,
        @WebParam(name = "sequence", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        long sequence,
        @WebParam(name = "utcDateStamp", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        XMLGregorianCalendar utcDateStamp,
        @WebParam(name = "title", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String title,
        @WebParam(name = "location", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String location,
        @WebParam(name = "utcDateStart", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        XMLGregorianCalendar utcDateStart,
        @WebParam(name = "utcDateEnd", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        XMLGregorianCalendar utcDateEnd,
        @WebParam(name = "nonGregorian", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        boolean nonGregorian);

    /**
     * 
     * @param ignoreAttendees
     * @param icalText
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.UpdateMeetingFromICalResponse.UpdateMeetingFromICalResult
     */
    @WebMethod(operationName = "UpdateMeetingFromICal", action = "http://schemas.microsoft.com/sharepoint/soap/meetings/UpdateMeetingFromICal")
    @WebResult(name = "UpdateMeetingFromICalResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
    @RequestWrapper(localName = "UpdateMeetingFromICal", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.UpdateMeetingFromICal")
    @ResponseWrapper(localName = "UpdateMeetingFromICalResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.UpdateMeetingFromICalResponse")
    public com.microsoft.schemas.sharepoint.soap.UpdateMeetingFromICalResponse.UpdateMeetingFromICalResult updateMeetingFromICal(
        @WebParam(name = "icalText", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String icalText,
        @WebParam(name = "ignoreAttendees", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        boolean ignoreAttendees);

    /**
     * 
     * @param uid
     * @param title
     * @param utcDateStamp
     * @param location
     * @param sequence
     * @param utcDateEnd
     * @param nonGregorian
     * @param utcDateStart
     */
    @WebMethod(operationName = "UpdateMeeting", action = "http://schemas.microsoft.com/sharepoint/soap/meetings/UpdateMeeting")
    @RequestWrapper(localName = "UpdateMeeting", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.UpdateMeeting")
    @ResponseWrapper(localName = "UpdateMeetingResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.UpdateMeetingResponse")
    public void updateMeeting(
        @WebParam(name = "uid", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String uid,
        @WebParam(name = "sequence", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        long sequence,
        @WebParam(name = "utcDateStamp", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        XMLGregorianCalendar utcDateStamp,
        @WebParam(name = "title", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String title,
        @WebParam(name = "location", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String location,
        @WebParam(name = "utcDateStart", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        XMLGregorianCalendar utcDateStart,
        @WebParam(name = "utcDateEnd", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        XMLGregorianCalendar utcDateEnd,
        @WebParam(name = "nonGregorian", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        boolean nonGregorian);

    /**
     * 
     * @param uid
     * @param utcDateStamp
     * @param sequence
     * @param recurrenceId
     * @param cancelMeeting
     */
    @WebMethod(operationName = "RemoveMeeting", action = "http://schemas.microsoft.com/sharepoint/soap/meetings/RemoveMeeting")
    @RequestWrapper(localName = "RemoveMeeting", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.RemoveMeeting")
    @ResponseWrapper(localName = "RemoveMeetingResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.RemoveMeetingResponse")
    public void removeMeeting(
        @WebParam(name = "recurrenceId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        long recurrenceId,
        @WebParam(name = "uid", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String uid,
        @WebParam(name = "sequence", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        long sequence,
        @WebParam(name = "utcDateStamp", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        XMLGregorianCalendar utcDateStamp,
        @WebParam(name = "cancelMeeting", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        boolean cancelMeeting);

    /**
     * 
     * @param response
     * @param uid
     * @param utcDateTimeAttendeeCriticalChange
     * @param sequence
     * @param recurrenceId
     * @param attendeeEmail
     * @param utcDateTimeOrganizerCriticalChange
     */
    @WebMethod(operationName = "SetAttendeeResponse", action = "http://schemas.microsoft.com/sharepoint/soap/meetings/SetAttendeeResponse")
    @RequestWrapper(localName = "SetAttendeeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.SetAttendeeResponse")
    @ResponseWrapper(localName = "SetAttendeeResponseResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.SetAttendeeResponseResponse")
    public void setAttendeeResponse(
        @WebParam(name = "attendeeEmail", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String attendeeEmail,
        @WebParam(name = "recurrenceId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        long recurrenceId,
        @WebParam(name = "uid", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String uid,
        @WebParam(name = "sequence", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        long sequence,
        @WebParam(name = "utcDateTimeOrganizerCriticalChange", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        XMLGregorianCalendar utcDateTimeOrganizerCriticalChange,
        @WebParam(name = "utcDateTimeAttendeeCriticalChange", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        XMLGregorianCalendar utcDateTimeAttendeeCriticalChange,
        @WebParam(name = "response", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        AttendeeResponse response);

    /**
     * 
     * @param lcid
     * @param requestFlags
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetMeetingsInformationResponse.GetMeetingsInformationResult
     */
    @WebMethod(operationName = "GetMeetingsInformation", action = "http://schemas.microsoft.com/sharepoint/soap/meetings/GetMeetingsInformation")
    @WebResult(name = "GetMeetingsInformationResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
    @RequestWrapper(localName = "GetMeetingsInformation", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.GetMeetingsInformation")
    @ResponseWrapper(localName = "GetMeetingsInformationResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.GetMeetingsInformationResponse")
    public com.microsoft.schemas.sharepoint.soap.GetMeetingsInformationResponse.GetMeetingsInformationResult getMeetingsInformation(
        @WebParam(name = "requestFlags", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        long requestFlags,
        @WebParam(name = "lcid", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        long lcid);

    /**
     * 
     * @param uid
     */
    @WebMethod(operationName = "RestoreMeeting", action = "http://schemas.microsoft.com/sharepoint/soap/meetings/RestoreMeeting")
    @RequestWrapper(localName = "RestoreMeeting", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.RestoreMeeting")
    @ResponseWrapper(localName = "RestoreMeetingResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/", className = "com.microsoft.schemas.sharepoint.soap.RestoreMeetingResponse")
    public void restoreMeeting(
        @WebParam(name = "uid", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/meetings/")
        String uid);

}
