
package com.microsoft.schemas.sharepoint.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "People", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", wsdlLocation = "file:/C:/Users/matko/Desktop/wsdl/people.wsdl")
public class People
    extends Service
{

    private final static URL PEOPLE_WSDL_LOCATION;
    private final static WebServiceException PEOPLE_EXCEPTION;
    private final static QName PEOPLE_QNAME = new QName("http://schemas.microsoft.com/sharepoint/soap/", "People");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/matko/Desktop/wsdl/people.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PEOPLE_WSDL_LOCATION = url;
        PEOPLE_EXCEPTION = e;
    }

    public People() {
        super(__getWsdlLocation(), PEOPLE_QNAME);
    }

    public People(WebServiceFeature... features) {
        super(__getWsdlLocation(), PEOPLE_QNAME, features);
    }

    public People(URL wsdlLocation) {
        super(wsdlLocation, PEOPLE_QNAME);
    }

    public People(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PEOPLE_QNAME, features);
    }

    public People(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public People(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PeopleSoap
     */
    @WebEndpoint(name = "PeopleSoap")
    public PeopleSoap getPeopleSoap() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "PeopleSoap"), PeopleSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PeopleSoap
     */
    @WebEndpoint(name = "PeopleSoap")
    public PeopleSoap getPeopleSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "PeopleSoap"), PeopleSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PeopleSoap
     */
    @WebEndpoint(name = "PeopleSoap12")
    public PeopleSoap getPeopleSoap12() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "PeopleSoap12"), PeopleSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PeopleSoap
     */
    @WebEndpoint(name = "PeopleSoap12")
    public PeopleSoap getPeopleSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "PeopleSoap12"), PeopleSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PEOPLE_EXCEPTION!= null) {
            throw PEOPLE_EXCEPTION;
        }
        return PEOPLE_WSDL_LOCATION;
    }

}
