
package com.microsoft.schemas.sharepoint.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PermissionsSoap", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PermissionsSoap {


    /**
     * 
     * @param objectName
     * @param objectType
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetPermissionCollectionResponse.GetPermissionCollectionResult
     */
    @WebMethod(operationName = "GetPermissionCollection", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetPermissionCollection")
    @WebResult(name = "GetPermissionCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetPermissionCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetPermissionCollection")
    @ResponseWrapper(localName = "GetPermissionCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetPermissionCollectionResponse")
    public com.microsoft.schemas.sharepoint.soap.GetPermissionCollectionResponse.GetPermissionCollectionResult getPermissionCollection(
        @WebParam(name = "objectName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String objectName,
        @WebParam(name = "objectType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String objectType);

    /**
     * 
     * @param objectName
     * @param permissionMask
     * @param permissionIdentifier
     * @param objectType
     * @param permissionType
     */
    @WebMethod(operationName = "AddPermission", action = "http://schemas.microsoft.com/sharepoint/soap/directory/AddPermission")
    @RequestWrapper(localName = "AddPermission", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddPermission")
    @ResponseWrapper(localName = "AddPermissionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddPermissionResponse")
    public void addPermission(
        @WebParam(name = "objectName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String objectName,
        @WebParam(name = "objectType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String objectType,
        @WebParam(name = "permissionIdentifier", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String permissionIdentifier,
        @WebParam(name = "permissionType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String permissionType,
        @WebParam(name = "permissionMask", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        int permissionMask);

    /**
     * 
     * @param permissionsInfoXml
     * @param objectName
     * @param objectType
     */
    @WebMethod(operationName = "AddPermissionCollection", action = "http://schemas.microsoft.com/sharepoint/soap/directory/AddPermissionCollection")
    @RequestWrapper(localName = "AddPermissionCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddPermissionCollection")
    @ResponseWrapper(localName = "AddPermissionCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddPermissionCollectionResponse")
    public void addPermissionCollection(
        @WebParam(name = "objectName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String objectName,
        @WebParam(name = "objectType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String objectType,
        @WebParam(name = "permissionsInfoXml", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        com.microsoft.schemas.sharepoint.soap.AddPermissionCollection.PermissionsInfoXml permissionsInfoXml);

    /**
     * 
     * @param objectName
     * @param permissionMask
     * @param permissionIdentifier
     * @param objectType
     * @param permissionType
     */
    @WebMethod(operationName = "UpdatePermission", action = "http://schemas.microsoft.com/sharepoint/soap/directory/UpdatePermission")
    @RequestWrapper(localName = "UpdatePermission", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.UpdatePermission")
    @ResponseWrapper(localName = "UpdatePermissionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.UpdatePermissionResponse")
    public void updatePermission(
        @WebParam(name = "objectName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String objectName,
        @WebParam(name = "objectType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String objectType,
        @WebParam(name = "permissionIdentifier", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String permissionIdentifier,
        @WebParam(name = "permissionType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String permissionType,
        @WebParam(name = "permissionMask", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        int permissionMask);

    /**
     * 
     * @param objectName
     * @param permissionIdentifier
     * @param objectType
     * @param permissionType
     */
    @WebMethod(operationName = "RemovePermission", action = "http://schemas.microsoft.com/sharepoint/soap/directory/RemovePermission")
    @RequestWrapper(localName = "RemovePermission", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemovePermission")
    @ResponseWrapper(localName = "RemovePermissionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemovePermissionResponse")
    public void removePermission(
        @WebParam(name = "objectName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String objectName,
        @WebParam(name = "objectType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String objectType,
        @WebParam(name = "permissionIdentifier", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String permissionIdentifier,
        @WebParam(name = "permissionType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String permissionType);

    /**
     * 
     * @param objectName
     * @param objectType
     * @param memberIdsXml
     */
    @WebMethod(operationName = "RemovePermissionCollection", action = "http://schemas.microsoft.com/sharepoint/soap/directory/RemovePermissionCollection")
    @RequestWrapper(localName = "RemovePermissionCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemovePermissionCollection")
    @ResponseWrapper(localName = "RemovePermissionCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemovePermissionCollectionResponse")
    public void removePermissionCollection(
        @WebParam(name = "objectName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String objectName,
        @WebParam(name = "objectType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String objectType,
        @WebParam(name = "memberIdsXml", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        com.microsoft.schemas.sharepoint.soap.RemovePermissionCollection.MemberIdsXml memberIdsXml);

}
