
package com.microsoft.schemas.sharepoint.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublishedLinksService", targetNamespace = "http://microsoft.com/webservices/SharePointPortalServer/PublishedLinksService", wsdlLocation = "file:/C:/Users/matko/Desktop/wsdl/publishedlinksservice.wsdl")
public class PublishedLinksService
    extends Service
{

    private final static URL PUBLISHEDLINKSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLISHEDLINKSSERVICE_EXCEPTION;
    private final static QName PUBLISHEDLINKSSERVICE_QNAME = new QName("http://microsoft.com/webservices/SharePointPortalServer/PublishedLinksService", "PublishedLinksService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/matko/Desktop/wsdl/publishedlinksservice.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLISHEDLINKSSERVICE_WSDL_LOCATION = url;
        PUBLISHEDLINKSSERVICE_EXCEPTION = e;
    }

    public PublishedLinksService() {
        super(__getWsdlLocation(), PUBLISHEDLINKSSERVICE_QNAME);
    }

    public PublishedLinksService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLISHEDLINKSSERVICE_QNAME, features);
    }

    public PublishedLinksService(URL wsdlLocation) {
        super(wsdlLocation, PUBLISHEDLINKSSERVICE_QNAME);
    }

    public PublishedLinksService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLISHEDLINKSSERVICE_QNAME, features);
    }

    public PublishedLinksService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublishedLinksService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublishedLinksServiceSoap
     */
    @WebEndpoint(name = "PublishedLinksServiceSoap")
    public PublishedLinksServiceSoap getPublishedLinksServiceSoap() {
        return super.getPort(new QName("http://microsoft.com/webservices/SharePointPortalServer/PublishedLinksService", "PublishedLinksServiceSoap"), PublishedLinksServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublishedLinksServiceSoap
     */
    @WebEndpoint(name = "PublishedLinksServiceSoap")
    public PublishedLinksServiceSoap getPublishedLinksServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://microsoft.com/webservices/SharePointPortalServer/PublishedLinksService", "PublishedLinksServiceSoap"), PublishedLinksServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PublishedLinksServiceSoap
     */
    @WebEndpoint(name = "PublishedLinksServiceSoap12")
    public PublishedLinksServiceSoap getPublishedLinksServiceSoap12() {
        return super.getPort(new QName("http://microsoft.com/webservices/SharePointPortalServer/PublishedLinksService", "PublishedLinksServiceSoap12"), PublishedLinksServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublishedLinksServiceSoap
     */
    @WebEndpoint(name = "PublishedLinksServiceSoap12")
    public PublishedLinksServiceSoap getPublishedLinksServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://microsoft.com/webservices/SharePointPortalServer/PublishedLinksService", "PublishedLinksServiceSoap12"), PublishedLinksServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLISHEDLINKSSERVICE_EXCEPTION!= null) {
            throw PUBLISHEDLINKSSERVICE_EXCEPTION;
        }
        return PUBLISHEDLINKSSERVICE_WSDL_LOCATION;
    }

}
