
package com.microsoft.schemas.sharepoint.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QueryServiceSoap", targetNamespace = "http://microsoft.com/webservices/SharePoint/QueryService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryServiceSoap {


    /**
     * 
     * @param queryXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Query", action = "urn:Microsoft.Search/Query")
    @WebResult(name = "QueryResult", targetNamespace = "urn:Microsoft.Search")
    @RequestWrapper(localName = "Query", targetNamespace = "urn:Microsoft.Search", className = "com.microsoft.schemas.sharepoint.soap.Query")
    @ResponseWrapper(localName = "QueryResponse", targetNamespace = "urn:Microsoft.Search", className = "com.microsoft.schemas.sharepoint.soap.QueryResponse")
    public String query(
        @WebParam(name = "queryXml", targetNamespace = "urn:Microsoft.Search")
        String queryXml);

    /**
     * 
     * @param queryXml
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.QueryExResponse.QueryExResult
     */
    @WebMethod(operationName = "QueryEx", action = "http://microsoft.com/webservices/SharePoint/QueryService/QueryEx")
    @WebResult(name = "QueryExResult", targetNamespace = "http://microsoft.com/webservices/SharePoint/QueryService")
    @RequestWrapper(localName = "QueryEx", targetNamespace = "http://microsoft.com/webservices/SharePoint/QueryService", className = "com.microsoft.schemas.sharepoint.soap.QueryEx")
    @ResponseWrapper(localName = "QueryExResponse", targetNamespace = "http://microsoft.com/webservices/SharePoint/QueryService", className = "com.microsoft.schemas.sharepoint.soap.QueryExResponse")
    public com.microsoft.schemas.sharepoint.soap.QueryExResponse.QueryExResult queryEx(
        @WebParam(name = "queryXml", targetNamespace = "http://microsoft.com/webservices/SharePoint/QueryService")
        String queryXml);

    /**
     * 
     * @param registrationXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Registration", action = "urn:Microsoft.Search/Registration")
    @WebResult(name = "RegistrationResult", targetNamespace = "urn:Microsoft.Search")
    @RequestWrapper(localName = "Registration", targetNamespace = "urn:Microsoft.Search", className = "com.microsoft.schemas.sharepoint.soap.Registration")
    @ResponseWrapper(localName = "RegistrationResponse", targetNamespace = "urn:Microsoft.Search", className = "com.microsoft.schemas.sharepoint.soap.RegistrationResponse")
    public String registration(
        @WebParam(name = "registrationXml", targetNamespace = "urn:Microsoft.Search")
        String registrationXml);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Status", action = "urn:Microsoft.Search/Status")
    @WebResult(name = "StatusResult", targetNamespace = "urn:Microsoft.Search")
    @RequestWrapper(localName = "Status", targetNamespace = "urn:Microsoft.Search", className = "com.microsoft.schemas.sharepoint.soap.Status")
    @ResponseWrapper(localName = "StatusResponse", targetNamespace = "urn:Microsoft.Search", className = "com.microsoft.schemas.sharepoint.soap.StatusResponse")
    public String status();

}
