
package com.microsoft.schemas.sharepoint.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Sharepoint Email Integration Web Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SharepointEmailWS", targetNamespace = "http://microsoft.com/webservices/SharePoint/SharepointEmailWS/", wsdlLocation = "file:/C:/Users/matko/Desktop/wsdl/sharepointemailws.wsdl")
public class SharepointEmailWS
    extends Service
{

    private final static URL SHAREPOINTEMAILWS_WSDL_LOCATION;
    private final static WebServiceException SHAREPOINTEMAILWS_EXCEPTION;
    private final static QName SHAREPOINTEMAILWS_QNAME = new QName("http://microsoft.com/webservices/SharePoint/SharepointEmailWS/", "SharepointEmailWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/matko/Desktop/wsdl/sharepointemailws.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHAREPOINTEMAILWS_WSDL_LOCATION = url;
        SHAREPOINTEMAILWS_EXCEPTION = e;
    }

    public SharepointEmailWS() {
        super(__getWsdlLocation(), SHAREPOINTEMAILWS_QNAME);
    }

    public SharepointEmailWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHAREPOINTEMAILWS_QNAME, features);
    }

    public SharepointEmailWS(URL wsdlLocation) {
        super(wsdlLocation, SHAREPOINTEMAILWS_QNAME);
    }

    public SharepointEmailWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHAREPOINTEMAILWS_QNAME, features);
    }

    public SharepointEmailWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SharepointEmailWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SharepointEmailWSSoap
     */
    @WebEndpoint(name = "SharepointEmailWSSoap")
    public SharepointEmailWSSoap getSharepointEmailWSSoap() {
        return super.getPort(new QName("http://microsoft.com/webservices/SharePoint/SharepointEmailWS/", "SharepointEmailWSSoap"), SharepointEmailWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SharepointEmailWSSoap
     */
    @WebEndpoint(name = "SharepointEmailWSSoap")
    public SharepointEmailWSSoap getSharepointEmailWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://microsoft.com/webservices/SharePoint/SharepointEmailWS/", "SharepointEmailWSSoap"), SharepointEmailWSSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns SharepointEmailWSSoap
     */
    @WebEndpoint(name = "SharepointEmailWSSoap12")
    public SharepointEmailWSSoap getSharepointEmailWSSoap12() {
        return super.getPort(new QName("http://microsoft.com/webservices/SharePoint/SharepointEmailWS/", "SharepointEmailWSSoap12"), SharepointEmailWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SharepointEmailWSSoap
     */
    @WebEndpoint(name = "SharepointEmailWSSoap12")
    public SharepointEmailWSSoap getSharepointEmailWSSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://microsoft.com/webservices/SharePoint/SharepointEmailWS/", "SharepointEmailWSSoap12"), SharepointEmailWSSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHAREPOINTEMAILWS_EXCEPTION!= null) {
            throw SHAREPOINTEMAILWS_EXCEPTION;
        }
        return SHAREPOINTEMAILWS_WSDL_LOCATION;
    }

}
