
package com.microsoft.schemas.sharepoint.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Sites", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", wsdlLocation = "file:/C:/Users/matko/Desktop/wsdl/sites.wsdl")
public class Sites
    extends Service
{

    private final static URL SITES_WSDL_LOCATION;
    private final static WebServiceException SITES_EXCEPTION;
    private final static QName SITES_QNAME = new QName("http://schemas.microsoft.com/sharepoint/soap/", "Sites");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/matko/Desktop/wsdl/sites.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SITES_WSDL_LOCATION = url;
        SITES_EXCEPTION = e;
    }

    public Sites() {
        super(__getWsdlLocation(), SITES_QNAME);
    }

    public Sites(WebServiceFeature... features) {
        super(__getWsdlLocation(), SITES_QNAME, features);
    }

    public Sites(URL wsdlLocation) {
        super(wsdlLocation, SITES_QNAME);
    }

    public Sites(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SITES_QNAME, features);
    }

    public Sites(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Sites(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SitesSoap
     */
    @WebEndpoint(name = "SitesSoap")
    public SitesSoap getSitesSoap() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "SitesSoap"), SitesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SitesSoap
     */
    @WebEndpoint(name = "SitesSoap")
    public SitesSoap getSitesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "SitesSoap"), SitesSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns SitesSoap
     */
    @WebEndpoint(name = "SitesSoap12")
    public SitesSoap getSitesSoap12() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "SitesSoap12"), SitesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SitesSoap
     */
    @WebEndpoint(name = "SitesSoap12")
    public SitesSoap getSitesSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "SitesSoap12"), SitesSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SITES_EXCEPTION!= null) {
            throw SITES_EXCEPTION;
        }
        return SITES_WSDL_LOCATION;
    }

}
