
package com.microsoft.schemas.sharepoint.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SiteDataSoap", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SiteDataSoap {


    /**
     * 
     * @param strWeb
     * @param strUrl
     * @param strSite
     * @param getSiteAndWebResult
     */
    @WebMethod(operationName = "GetSiteAndWeb", action = "http://schemas.microsoft.com/sharepoint/soap/GetSiteAndWeb")
    @RequestWrapper(localName = "GetSiteAndWeb", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetSiteAndWeb")
    @ResponseWrapper(localName = "GetSiteAndWebResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetSiteAndWebResponse")
    public void getSiteAndWeb(
        @WebParam(name = "strUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strUrl,
        @WebParam(name = "GetSiteAndWebResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<Long> getSiteAndWebResult,
        @WebParam(name = "strSite", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<String> strSite,
        @WebParam(name = "strWeb", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<String> strWeb);

    /**
     * 
     * @param strGroups
     * @param vGroups
     * @param vWebs
     * @param getSiteResult
     * @param sSiteMetadata
     * @param strUsers
     */
    @WebMethod(operationName = "GetSite", action = "http://schemas.microsoft.com/sharepoint/soap/GetSite")
    @RequestWrapper(localName = "GetSite", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetSite")
    @ResponseWrapper(localName = "GetSiteResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetSiteResponse")
    public void getSite(
        @WebParam(name = "GetSiteResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<Long> getSiteResult,
        @WebParam(name = "sSiteMetadata", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<SSiteMetadata> sSiteMetadata,
        @WebParam(name = "vWebs", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfSWebWithTime> vWebs,
        @WebParam(name = "strUsers", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<String> strUsers,
        @WebParam(name = "strGroups", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<String> strGroups,
        @WebParam(name = "vGroups", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfString> vGroups);

    /**
     * 
     * @param strRoles
     * @param vRolesGroups
     * @param getWebResult
     * @param vWebs
     * @param vFPUrls
     * @param sWebMetadata
     * @param vLists
     * @param vRolesUsers
     */
    @WebMethod(operationName = "GetWeb", action = "http://schemas.microsoft.com/sharepoint/soap/GetWeb")
    @RequestWrapper(localName = "GetWeb", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetWeb")
    @ResponseWrapper(localName = "GetWebResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetWebResponse")
    public void getWeb(
        @WebParam(name = "GetWebResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<Long> getWebResult,
        @WebParam(name = "sWebMetadata", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<SWebMetadata> sWebMetadata,
        @WebParam(name = "vWebs", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfSWebWithTime> vWebs,
        @WebParam(name = "vLists", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfSListWithTime> vLists,
        @WebParam(name = "vFPUrls", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfSFPUrl> vFPUrls,
        @WebParam(name = "strRoles", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<String> strRoles,
        @WebParam(name = "vRolesUsers", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfString> vRolesUsers,
        @WebParam(name = "vRolesGroups", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfString> vRolesGroups);

    /**
     * 
     * @param getListResult
     * @param vProperties
     * @param sListMetadata
     * @param strListName
     */
    @WebMethod(operationName = "GetList", action = "http://schemas.microsoft.com/sharepoint/soap/GetList")
    @RequestWrapper(localName = "GetList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetList")
    @ResponseWrapper(localName = "GetListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListResponse")
    public void getList(
        @WebParam(name = "strListName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strListName,
        @WebParam(name = "GetListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<Long> getListResult,
        @WebParam(name = "sListMetadata", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<SListMetadata> sListMetadata,
        @WebParam(name = "vProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfSProperty> vProperties);

    /**
     * 
     * @param uRowLimit
     * @param strViewFields
     * @param strQuery
     * @param strListName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetListItems", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItems")
    @WebResult(name = "GetListItemsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListItems", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListItems")
    @ResponseWrapper(localName = "GetListItemsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListItemsResponse")
    public String getListItems(
        @WebParam(name = "strListName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strListName,
        @WebParam(name = "strQuery", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strQuery,
        @WebParam(name = "strViewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strViewFields,
        @WebParam(name = "uRowLimit", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        long uRowLimit);

    /**
     * 
     * @param vUrls
     * @param strFolderUrl
     * @param enumerateFolderResult
     */
    @WebMethod(operationName = "EnumerateFolder", action = "http://schemas.microsoft.com/sharepoint/soap/EnumerateFolder")
    @RequestWrapper(localName = "EnumerateFolder", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.EnumerateFolder")
    @ResponseWrapper(localName = "EnumerateFolderResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.EnumerateFolderResponse")
    public void enumerateFolder(
        @WebParam(name = "strFolderUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strFolderUrl,
        @WebParam(name = "EnumerateFolderResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<Long> enumerateFolderResult,
        @WebParam(name = "vUrls", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfSFPUrl> vUrls);

    /**
     * 
     * @param getAttachmentsResult
     * @param strListName
     * @param strItemId
     * @param vAttachments
     */
    @WebMethod(operationName = "GetAttachments", action = "http://schemas.microsoft.com/sharepoint/soap/GetAttachments")
    @RequestWrapper(localName = "GetAttachments", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetAttachments")
    @ResponseWrapper(localName = "GetAttachmentsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetAttachmentsResponse")
    public void getAttachments(
        @WebParam(name = "strListName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strListName,
        @WebParam(name = "strItemId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strItemId,
        @WebParam(name = "GetAttachmentsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<Long> getAttachmentsResult,
        @WebParam(name = "vAttachments", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfString> vAttachments);

    /**
     * 
     * @param strItemID
     * @param strWebID
     * @param strListID
     * @param getURLSegmentsResult
     * @param strURL
     * @param strBucketID
     */
    @WebMethod(operationName = "GetURLSegments", action = "http://schemas.microsoft.com/sharepoint/soap/GetURLSegments")
    @RequestWrapper(localName = "GetURLSegments", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetURLSegments")
    @ResponseWrapper(localName = "GetURLSegmentsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetURLSegmentsResponse")
    public void getURLSegments(
        @WebParam(name = "strURL", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strURL,
        @WebParam(name = "GetURLSegmentsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<Boolean> getURLSegmentsResult,
        @WebParam(name = "strWebID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<String> strWebID,
        @WebParam(name = "strBucketID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<String> strBucketID,
        @WebParam(name = "strListID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<String> strListID,
        @WebParam(name = "strItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<String> strItemID);

    /**
     * 
     * @param getListCollectionResult
     * @param vLists
     */
    @WebMethod(operationName = "GetListCollection", action = "http://schemas.microsoft.com/sharepoint/soap/GetListCollection")
    @RequestWrapper(localName = "GetListCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListCollection")
    @ResponseWrapper(localName = "GetListCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetListCollectionResponse")
    public void getListCollection(
        @WebParam(name = "GetListCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<Long> getListCollectionResult,
        @WebParam(name = "vLists", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfSList> vLists);

    /**
     * 
     * @param lastItemIdOnPage
     * @param objectId
     * @param securityOnly
     * @param folderUrl
     * @param itemId
     * @param objectType
     * @param getContentResult
     * @param retrieveChildItems
     */
    @WebMethod(operationName = "GetContent", action = "http://schemas.microsoft.com/sharepoint/soap/GetContent")
    @RequestWrapper(localName = "GetContent", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetContent")
    @ResponseWrapper(localName = "GetContentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetContentResponse")
    public void getContent(
        @WebParam(name = "objectType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        ObjectType objectType,
        @WebParam(name = "objectId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String objectId,
        @WebParam(name = "folderUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String folderUrl,
        @WebParam(name = "itemId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String itemId,
        @WebParam(name = "retrieveChildItems", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        boolean retrieveChildItems,
        @WebParam(name = "securityOnly", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        boolean securityOnly,
        @WebParam(name = "lastItemIdOnPage", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.INOUT)
        Holder<String> lastItemIdOnPage,
        @WebParam(name = "GetContentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<String> getContentResult);

    /**
     * 
     * @param siteUrl
     * @param siteId
     * @param getSiteUrlResult
     * @param url
     */
    @WebMethod(operationName = "GetSiteUrl", action = "http://schemas.microsoft.com/sharepoint/soap/GetSiteUrl")
    @RequestWrapper(localName = "GetSiteUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetSiteUrl")
    @ResponseWrapper(localName = "GetSiteUrlResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetSiteUrlResponse")
    public void getSiteUrl(
        @WebParam(name = "Url", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String url,
        @WebParam(name = "GetSiteUrlResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<Long> getSiteUrlResult,
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<String> siteUrl,
        @WebParam(name = "siteId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<String> siteId);

    /**
     * 
     * @param getChangesResult
     * @param contentDatabaseId
     * @param lastChangeId
     * @param currentChangeId
     * @param moreChanges
     * @param objectType
     * @param timeout
     */
    @WebMethod(operationName = "GetChanges", action = "http://schemas.microsoft.com/sharepoint/soap/GetChanges")
    @RequestWrapper(localName = "GetChanges", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetChanges")
    @ResponseWrapper(localName = "GetChangesResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetChangesResponse")
    public void getChanges(
        @WebParam(name = "objectType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        ObjectType objectType,
        @WebParam(name = "contentDatabaseId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentDatabaseId,
        @WebParam(name = "LastChangeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.INOUT)
        Holder<String> lastChangeId,
        @WebParam(name = "CurrentChangeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.INOUT)
        Holder<String> currentChangeId,
        @WebParam(name = "Timeout", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        int timeout,
        @WebParam(name = "GetChangesResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<String> getChangesResult,
        @WebParam(name = "moreChanges", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<Boolean> moreChanges);

}
