
package com.microsoft.schemas.sharepoint.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SitesSoap", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SitesSoap {


    /**
     * 
     * @param lcid
     * @param getSiteTemplatesResult
     * @param templateList
     */
    @WebMethod(operationName = "GetSiteTemplates", action = "http://schemas.microsoft.com/sharepoint/soap/GetSiteTemplates")
    @RequestWrapper(localName = "GetSiteTemplates", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetSiteTemplates")
    @ResponseWrapper(localName = "GetSiteTemplatesResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetSiteTemplatesResponse")
    public void getSiteTemplates(
        @WebParam(name = "LCID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        long lcid,
        @WebParam(name = "GetSiteTemplatesResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<Long> getSiteTemplatesResult,
        @WebParam(name = "TemplateList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfTemplate> templateList);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUpdatedFormDigest", action = "http://schemas.microsoft.com/sharepoint/soap/GetUpdatedFormDigest")
    @WebResult(name = "GetUpdatedFormDigestResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetUpdatedFormDigest", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetUpdatedFormDigest")
    @ResponseWrapper(localName = "GetUpdatedFormDigestResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.GetUpdatedFormDigestResponse")
    public String getUpdatedFormDigest();

    /**
     * 
     * @param cabSize
     * @param webUrl
     * @param dataPath
     * @param includeSubwebs
     * @param overWrite
     * @param includeUserSecurity
     * @param jobName
     * @return
     *     returns int
     */
    @WebMethod(operationName = "ExportWeb", action = "http://schemas.microsoft.com/sharepoint/soap/ExportWeb")
    @WebResult(name = "ExportWebResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "ExportWeb", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.ExportWeb")
    @ResponseWrapper(localName = "ExportWebResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.ExportWebResponse")
    public int exportWeb(
        @WebParam(name = "jobName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String jobName,
        @WebParam(name = "webUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String webUrl,
        @WebParam(name = "dataPath", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String dataPath,
        @WebParam(name = "includeSubwebs", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        boolean includeSubwebs,
        @WebParam(name = "includeUserSecurity", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        boolean includeUserSecurity,
        @WebParam(name = "overWrite", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        boolean overWrite,
        @WebParam(name = "cabSize", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        int cabSize);

    /**
     * 
     * @param webUrl
     * @param logPath
     * @param overWrite
     * @param includeUserSecurity
     * @param dataFiles
     * @param jobName
     * @return
     *     returns int
     */
    @WebMethod(operationName = "ImportWeb", action = "http://schemas.microsoft.com/sharepoint/soap/ImportWeb")
    @WebResult(name = "ImportWebResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "ImportWeb", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.ImportWeb")
    @ResponseWrapper(localName = "ImportWebResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.schemas.sharepoint.soap.ImportWebResponse")
    public int importWeb(
        @WebParam(name = "jobName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String jobName,
        @WebParam(name = "webUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String webUrl,
        @WebParam(name = "dataFiles", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        ArrayOfString dataFiles,
        @WebParam(name = "logPath", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String logPath,
        @WebParam(name = "includeUserSecurity", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        boolean includeUserSecurity,
        @WebParam(name = "overWrite", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        boolean overWrite);

}
