
package com.microsoft.schemas.sharepoint.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SiteData", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", wsdlLocation = "file:/C:/Users/matko/Desktop/wsdl/sitedata.wsdl")
public class SiteData
    extends Service
{

    private final static URL SITEDATA_WSDL_LOCATION;
    private final static WebServiceException SITEDATA_EXCEPTION;
    private final static QName SITEDATA_QNAME = new QName("http://schemas.microsoft.com/sharepoint/soap/", "SiteData");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/matko/Desktop/wsdl/sitedata.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SITEDATA_WSDL_LOCATION = url;
        SITEDATA_EXCEPTION = e;
    }

    public SiteData() {
        super(__getWsdlLocation(), SITEDATA_QNAME);
    }

    public SiteData(WebServiceFeature... features) {
        super(__getWsdlLocation(), SITEDATA_QNAME, features);
    }

    public SiteData(URL wsdlLocation) {
        super(wsdlLocation, SITEDATA_QNAME);
    }

    public SiteData(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SITEDATA_QNAME, features);
    }

    public SiteData(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SiteData(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SiteDataSoap
     */
    @WebEndpoint(name = "SiteDataSoap")
    public SiteDataSoap getSiteDataSoap() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "SiteDataSoap"), SiteDataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SiteDataSoap
     */
    @WebEndpoint(name = "SiteDataSoap")
    public SiteDataSoap getSiteDataSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "SiteDataSoap"), SiteDataSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns SiteDataSoap
     */
    @WebEndpoint(name = "SiteDataSoap12")
    public SiteDataSoap getSiteDataSoap12() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "SiteDataSoap12"), SiteDataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SiteDataSoap
     */
    @WebEndpoint(name = "SiteDataSoap12")
    public SiteDataSoap getSiteDataSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "SiteDataSoap12"), SiteDataSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SITEDATA_EXCEPTION!= null) {
            throw SITEDATA_EXCEPTION;
        }
        return SITEDATA_WSDL_LOCATION;
    }

}
