
package com.microsoft.schemas.sharepoint.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StsAdapter", targetNamespace = "http://schemas.microsoft.com/sharepoint/dsp", wsdlLocation = "file:/C:/Users/matko/Desktop/wsdl/dspsts.wsdl")
public class StsAdapter
    extends Service
{

    private final static URL STSADAPTER_WSDL_LOCATION;
    private final static WebServiceException STSADAPTER_EXCEPTION;
    private final static QName STSADAPTER_QNAME = new QName("http://schemas.microsoft.com/sharepoint/dsp", "StsAdapter");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/matko/Desktop/wsdl/dspsts.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STSADAPTER_WSDL_LOCATION = url;
        STSADAPTER_EXCEPTION = e;
    }

    public StsAdapter() {
        super(__getWsdlLocation(), STSADAPTER_QNAME);
    }

    public StsAdapter(WebServiceFeature... features) {
        super(__getWsdlLocation(), STSADAPTER_QNAME, features);
    }

    public StsAdapter(URL wsdlLocation) {
        super(wsdlLocation, STSADAPTER_QNAME);
    }

    public StsAdapter(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STSADAPTER_QNAME, features);
    }

    public StsAdapter(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StsAdapter(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StsAdapterSoap
     */
    @WebEndpoint(name = "StsAdapterSoap")
    public StsAdapterSoap getStsAdapterSoap() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/dsp", "StsAdapterSoap"), StsAdapterSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StsAdapterSoap
     */
    @WebEndpoint(name = "StsAdapterSoap")
    public StsAdapterSoap getStsAdapterSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/dsp", "StsAdapterSoap"), StsAdapterSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns StsAdapterSoap
     */
    @WebEndpoint(name = "StsAdapterSoap12")
    public StsAdapterSoap getStsAdapterSoap12() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/dsp", "StsAdapterSoap12"), StsAdapterSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StsAdapterSoap
     */
    @WebEndpoint(name = "StsAdapterSoap12")
    public StsAdapterSoap getStsAdapterSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/dsp", "StsAdapterSoap12"), StsAdapterSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STSADAPTER_EXCEPTION!= null) {
            throw STSADAPTER_EXCEPTION;
        }
        return STSADAPTER_WSDL_LOCATION;
    }

}
