
package com.microsoft.schemas.sharepoint.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StsAdapterSoap", targetNamespace = "http://schemas.microsoft.com/sharepoint/dsp")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StsAdapterSoap {


    /**
     * 
     * @param request
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.QueryResponse
     */
    @WebMethod(operationName = "Query", action = "http://schemas.microsoft.com/sharepoint/dsp/queryRequest")
    @WebResult(name = "queryResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/dsp", partName = "queryRequestResult")
    public QueryResponse query(
        @WebParam(name = "queryRequest", targetNamespace = "http://schemas.microsoft.com/sharepoint/dsp", partName = "Request")
        QueryRequest request);

}
