
package com.microsoft.schemas.sharepoint.soap;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserGroupSoap", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserGroupSoap {


    /**
     * 
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromSiteResponse.GetUserCollectionFromSiteResult
     */
    @WebMethod(operationName = "GetUserCollectionFromSite", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetUserCollectionFromSite")
    @WebResult(name = "GetUserCollectionFromSiteResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetUserCollectionFromSite", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromSite")
    @ResponseWrapper(localName = "GetUserCollectionFromSiteResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromSiteResponse")
    public com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromSiteResponse.GetUserCollectionFromSiteResult getUserCollectionFromSite();

    /**
     * 
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromWebResponse.GetUserCollectionFromWebResult
     */
    @WebMethod(operationName = "GetUserCollectionFromWeb", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetUserCollectionFromWeb")
    @WebResult(name = "GetUserCollectionFromWebResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetUserCollectionFromWeb", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromWeb")
    @ResponseWrapper(localName = "GetUserCollectionFromWebResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromWebResponse")
    public com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromWebResponse.GetUserCollectionFromWebResult getUserCollectionFromWeb();

    /**
     * 
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetAllUserCollectionFromWebResponse.GetAllUserCollectionFromWebResult
     */
    @WebMethod(operationName = "GetAllUserCollectionFromWeb", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetAllUserCollectionFromWeb")
    @WebResult(name = "GetAllUserCollectionFromWebResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetAllUserCollectionFromWeb", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetAllUserCollectionFromWeb")
    @ResponseWrapper(localName = "GetAllUserCollectionFromWebResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetAllUserCollectionFromWebResponse")
    public com.microsoft.schemas.sharepoint.soap.GetAllUserCollectionFromWebResponse.GetAllUserCollectionFromWebResult getAllUserCollectionFromWeb();

    /**
     * 
     * @param groupName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromGroupResponse.GetUserCollectionFromGroupResult
     */
    @WebMethod(operationName = "GetUserCollectionFromGroup", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetUserCollectionFromGroup")
    @WebResult(name = "GetUserCollectionFromGroupResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetUserCollectionFromGroup", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromGroup")
    @ResponseWrapper(localName = "GetUserCollectionFromGroupResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromGroupResponse")
    public com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromGroupResponse.GetUserCollectionFromGroupResult getUserCollectionFromGroup(
        @WebParam(name = "groupName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String groupName);

    /**
     * 
     * @param roleName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromRoleResponse.GetUserCollectionFromRoleResult
     */
    @WebMethod(operationName = "GetUserCollectionFromRole", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetUserCollectionFromRole")
    @WebResult(name = "GetUserCollectionFromRoleResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetUserCollectionFromRole", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromRole")
    @ResponseWrapper(localName = "GetUserCollectionFromRoleResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromRoleResponse")
    public com.microsoft.schemas.sharepoint.soap.GetUserCollectionFromRoleResponse.GetUserCollectionFromRoleResult getUserCollectionFromRole(
        @WebParam(name = "roleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String roleName);

    /**
     * 
     * @param userLoginNamesXml
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetUserCollectionResponse.GetUserCollectionResult
     */
    @WebMethod(operationName = "GetUserCollection", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetUserCollection")
    @WebResult(name = "GetUserCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetUserCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetUserCollection")
    @ResponseWrapper(localName = "GetUserCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetUserCollectionResponse")
    public com.microsoft.schemas.sharepoint.soap.GetUserCollectionResponse.GetUserCollectionResult getUserCollection(
        @WebParam(name = "userLoginNamesXml", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        com.microsoft.schemas.sharepoint.soap.GetUserCollection.UserLoginNamesXml userLoginNamesXml);

    /**
     * 
     * @param userLoginName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetUserInfoResponse.GetUserInfoResult
     */
    @WebMethod(operationName = "GetUserInfo", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetUserInfo")
    @WebResult(name = "GetUserInfoResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetUserInfo", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetUserInfo")
    @ResponseWrapper(localName = "GetUserInfoResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetUserInfoResponse")
    public com.microsoft.schemas.sharepoint.soap.GetUserInfoResponse.GetUserInfoResult getUserInfo(
        @WebParam(name = "userLoginName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userLoginName);

    /**
     * 
     * @param groupName
     * @param userNotes
     * @param userName
     * @param userEmail
     * @param userLoginName
     */
    @WebMethod(operationName = "AddUserToGroup", action = "http://schemas.microsoft.com/sharepoint/soap/directory/AddUserToGroup")
    @RequestWrapper(localName = "AddUserToGroup", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddUserToGroup")
    @ResponseWrapper(localName = "AddUserToGroupResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddUserToGroupResponse")
    public void addUserToGroup(
        @WebParam(name = "groupName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String groupName,
        @WebParam(name = "userName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userName,
        @WebParam(name = "userLoginName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userLoginName,
        @WebParam(name = "userEmail", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userEmail,
        @WebParam(name = "userNotes", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userNotes);

    /**
     * 
     * @param usersInfoXml
     * @param groupName
     */
    @WebMethod(operationName = "AddUserCollectionToGroup", action = "http://schemas.microsoft.com/sharepoint/soap/directory/AddUserCollectionToGroup")
    @RequestWrapper(localName = "AddUserCollectionToGroup", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddUserCollectionToGroup")
    @ResponseWrapper(localName = "AddUserCollectionToGroupResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddUserCollectionToGroupResponse")
    public void addUserCollectionToGroup(
        @WebParam(name = "groupName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String groupName,
        @WebParam(name = "usersInfoXml", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        com.microsoft.schemas.sharepoint.soap.AddUserCollectionToGroup.UsersInfoXml usersInfoXml);

    /**
     * 
     * @param userNotes
     * @param userName
     * @param userEmail
     * @param roleName
     * @param userLoginName
     */
    @WebMethod(operationName = "AddUserToRole", action = "http://schemas.microsoft.com/sharepoint/soap/directory/AddUserToRole")
    @RequestWrapper(localName = "AddUserToRole", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddUserToRole")
    @ResponseWrapper(localName = "AddUserToRoleResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddUserToRoleResponse")
    public void addUserToRole(
        @WebParam(name = "roleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String roleName,
        @WebParam(name = "userName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userName,
        @WebParam(name = "userLoginName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userLoginName,
        @WebParam(name = "userEmail", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userEmail,
        @WebParam(name = "userNotes", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userNotes);

    /**
     * 
     * @param usersInfoXml
     * @param roleName
     */
    @WebMethod(operationName = "AddUserCollectionToRole", action = "http://schemas.microsoft.com/sharepoint/soap/directory/AddUserCollectionToRole")
    @RequestWrapper(localName = "AddUserCollectionToRole", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddUserCollectionToRole")
    @ResponseWrapper(localName = "AddUserCollectionToRoleResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddUserCollectionToRoleResponse")
    public void addUserCollectionToRole(
        @WebParam(name = "roleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String roleName,
        @WebParam(name = "usersInfoXml", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        com.microsoft.schemas.sharepoint.soap.AddUserCollectionToRole.UsersInfoXml usersInfoXml);

    /**
     * 
     * @param userNotes
     * @param userName
     * @param userEmail
     * @param userLoginName
     */
    @WebMethod(operationName = "UpdateUserInfo", action = "http://schemas.microsoft.com/sharepoint/soap/directory/UpdateUserInfo")
    @RequestWrapper(localName = "UpdateUserInfo", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.UpdateUserInfo")
    @ResponseWrapper(localName = "UpdateUserInfoResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.UpdateUserInfoResponse")
    public void updateUserInfo(
        @WebParam(name = "userLoginName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userLoginName,
        @WebParam(name = "userName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userName,
        @WebParam(name = "userEmail", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userEmail,
        @WebParam(name = "userNotes", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userNotes);

    /**
     * 
     * @param userLoginName
     */
    @WebMethod(operationName = "RemoveUserFromSite", action = "http://schemas.microsoft.com/sharepoint/soap/directory/RemoveUserFromSite")
    @RequestWrapper(localName = "RemoveUserFromSite", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveUserFromSite")
    @ResponseWrapper(localName = "RemoveUserFromSiteResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveUserFromSiteResponse")
    public void removeUserFromSite(
        @WebParam(name = "userLoginName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userLoginName);

    /**
     * 
     * @param userLoginNamesXml
     */
    @WebMethod(operationName = "RemoveUserCollectionFromSite", action = "http://schemas.microsoft.com/sharepoint/soap/directory/RemoveUserCollectionFromSite")
    @RequestWrapper(localName = "RemoveUserCollectionFromSite", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveUserCollectionFromSite")
    @ResponseWrapper(localName = "RemoveUserCollectionFromSiteResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveUserCollectionFromSiteResponse")
    public void removeUserCollectionFromSite(
        @WebParam(name = "userLoginNamesXml", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        com.microsoft.schemas.sharepoint.soap.RemoveUserCollectionFromSite.UserLoginNamesXml userLoginNamesXml);

    /**
     * 
     * @param userLoginName
     */
    @WebMethod(operationName = "RemoveUserFromWeb", action = "http://schemas.microsoft.com/sharepoint/soap/directory/RemoveUserFromWeb")
    @RequestWrapper(localName = "RemoveUserFromWeb", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveUserFromWeb")
    @ResponseWrapper(localName = "RemoveUserFromWebResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveUserFromWebResponse")
    public void removeUserFromWeb(
        @WebParam(name = "userLoginName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userLoginName);

    /**
     * 
     * @param groupName
     * @param userLoginName
     */
    @WebMethod(operationName = "RemoveUserFromGroup", action = "http://schemas.microsoft.com/sharepoint/soap/directory/RemoveUserFromGroup")
    @RequestWrapper(localName = "RemoveUserFromGroup", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveUserFromGroup")
    @ResponseWrapper(localName = "RemoveUserFromGroupResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveUserFromGroupResponse")
    public void removeUserFromGroup(
        @WebParam(name = "groupName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String groupName,
        @WebParam(name = "userLoginName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userLoginName);

    /**
     * 
     * @param userLoginNamesXml
     * @param groupName
     */
    @WebMethod(operationName = "RemoveUserCollectionFromGroup", action = "http://schemas.microsoft.com/sharepoint/soap/directory/RemoveUserCollectionFromGroup")
    @RequestWrapper(localName = "RemoveUserCollectionFromGroup", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveUserCollectionFromGroup")
    @ResponseWrapper(localName = "RemoveUserCollectionFromGroupResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveUserCollectionFromGroupResponse")
    public void removeUserCollectionFromGroup(
        @WebParam(name = "groupName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String groupName,
        @WebParam(name = "userLoginNamesXml", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        com.microsoft.schemas.sharepoint.soap.RemoveUserCollectionFromGroup.UserLoginNamesXml userLoginNamesXml);

    /**
     * 
     * @param roleName
     * @param userLoginName
     */
    @WebMethod(operationName = "RemoveUserFromRole", action = "http://schemas.microsoft.com/sharepoint/soap/directory/RemoveUserFromRole")
    @RequestWrapper(localName = "RemoveUserFromRole", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveUserFromRole")
    @ResponseWrapper(localName = "RemoveUserFromRoleResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveUserFromRoleResponse")
    public void removeUserFromRole(
        @WebParam(name = "roleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String roleName,
        @WebParam(name = "userLoginName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userLoginName);

    /**
     * 
     * @param userLoginNamesXml
     * @param roleName
     */
    @WebMethod(operationName = "RemoveUserCollectionFromRole", action = "http://schemas.microsoft.com/sharepoint/soap/directory/RemoveUserCollectionFromRole")
    @RequestWrapper(localName = "RemoveUserCollectionFromRole", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveUserCollectionFromRole")
    @ResponseWrapper(localName = "RemoveUserCollectionFromRoleResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveUserCollectionFromRoleResponse")
    public void removeUserCollectionFromRole(
        @WebParam(name = "roleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String roleName,
        @WebParam(name = "userLoginNamesXml", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        com.microsoft.schemas.sharepoint.soap.RemoveUserCollectionFromRole.UserLoginNamesXml userLoginNamesXml);

    /**
     * 
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromSiteResponse.GetGroupCollectionFromSiteResult
     */
    @WebMethod(operationName = "GetGroupCollectionFromSite", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetGroupCollectionFromSite")
    @WebResult(name = "GetGroupCollectionFromSiteResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetGroupCollectionFromSite", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromSite")
    @ResponseWrapper(localName = "GetGroupCollectionFromSiteResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromSiteResponse")
    public com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromSiteResponse.GetGroupCollectionFromSiteResult getGroupCollectionFromSite();

    /**
     * 
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromWebResponse.GetGroupCollectionFromWebResult
     */
    @WebMethod(operationName = "GetGroupCollectionFromWeb", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetGroupCollectionFromWeb")
    @WebResult(name = "GetGroupCollectionFromWebResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetGroupCollectionFromWeb", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromWeb")
    @ResponseWrapper(localName = "GetGroupCollectionFromWebResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromWebResponse")
    public com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromWebResponse.GetGroupCollectionFromWebResult getGroupCollectionFromWeb();

    /**
     * 
     * @param roleName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromRoleResponse.GetGroupCollectionFromRoleResult
     */
    @WebMethod(operationName = "GetGroupCollectionFromRole", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetGroupCollectionFromRole")
    @WebResult(name = "GetGroupCollectionFromRoleResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetGroupCollectionFromRole", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromRole")
    @ResponseWrapper(localName = "GetGroupCollectionFromRoleResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromRoleResponse")
    public com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromRoleResponse.GetGroupCollectionFromRoleResult getGroupCollectionFromRole(
        @WebParam(name = "roleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String roleName);

    /**
     * 
     * @param userLoginName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromUserResponse.GetGroupCollectionFromUserResult
     */
    @WebMethod(operationName = "GetGroupCollectionFromUser", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetGroupCollectionFromUser")
    @WebResult(name = "GetGroupCollectionFromUserResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetGroupCollectionFromUser", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromUser")
    @ResponseWrapper(localName = "GetGroupCollectionFromUserResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromUserResponse")
    public com.microsoft.schemas.sharepoint.soap.GetGroupCollectionFromUserResponse.GetGroupCollectionFromUserResult getGroupCollectionFromUser(
        @WebParam(name = "userLoginName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userLoginName);

    /**
     * 
     * @param groupNamesXml
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetGroupCollectionResponse.GetGroupCollectionResult
     */
    @WebMethod(operationName = "GetGroupCollection", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetGroupCollection")
    @WebResult(name = "GetGroupCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetGroupCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetGroupCollection")
    @ResponseWrapper(localName = "GetGroupCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetGroupCollectionResponse")
    public com.microsoft.schemas.sharepoint.soap.GetGroupCollectionResponse.GetGroupCollectionResult getGroupCollection(
        @WebParam(name = "groupNamesXml", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        com.microsoft.schemas.sharepoint.soap.GetGroupCollection.GroupNamesXml groupNamesXml);

    /**
     * 
     * @param groupName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetGroupInfoResponse.GetGroupInfoResult
     */
    @WebMethod(operationName = "GetGroupInfo", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetGroupInfo")
    @WebResult(name = "GetGroupInfoResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetGroupInfo", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetGroupInfo")
    @ResponseWrapper(localName = "GetGroupInfoResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetGroupInfoResponse")
    public com.microsoft.schemas.sharepoint.soap.GetGroupInfoResponse.GetGroupInfoResult getGroupInfo(
        @WebParam(name = "groupName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String groupName);

    /**
     * 
     * @param groupName
     * @param description
     * @param ownerIdentifier
     * @param ownerType
     * @param defaultUserLoginName
     */
    @WebMethod(operationName = "AddGroup", action = "http://schemas.microsoft.com/sharepoint/soap/directory/AddGroup")
    @RequestWrapper(localName = "AddGroup", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddGroup")
    @ResponseWrapper(localName = "AddGroupResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddGroupResponse")
    public void addGroup(
        @WebParam(name = "groupName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String groupName,
        @WebParam(name = "ownerIdentifier", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String ownerIdentifier,
        @WebParam(name = "ownerType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String ownerType,
        @WebParam(name = "defaultUserLoginName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String defaultUserLoginName,
        @WebParam(name = "description", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String description);

    /**
     * 
     * @param groupName
     * @param roleName
     */
    @WebMethod(operationName = "AddGroupToRole", action = "http://schemas.microsoft.com/sharepoint/soap/directory/AddGroupToRole")
    @RequestWrapper(localName = "AddGroupToRole", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddGroupToRole")
    @ResponseWrapper(localName = "AddGroupToRoleResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddGroupToRoleResponse")
    public void addGroupToRole(
        @WebParam(name = "roleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String roleName,
        @WebParam(name = "groupName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String groupName);

    /**
     * 
     * @param groupName
     * @param oldGroupName
     * @param description
     * @param ownerIdentifier
     * @param ownerType
     */
    @WebMethod(operationName = "UpdateGroupInfo", action = "http://schemas.microsoft.com/sharepoint/soap/directory/UpdateGroupInfo")
    @RequestWrapper(localName = "UpdateGroupInfo", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.UpdateGroupInfo")
    @ResponseWrapper(localName = "UpdateGroupInfoResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.UpdateGroupInfoResponse")
    public void updateGroupInfo(
        @WebParam(name = "oldGroupName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String oldGroupName,
        @WebParam(name = "groupName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String groupName,
        @WebParam(name = "ownerIdentifier", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String ownerIdentifier,
        @WebParam(name = "ownerType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String ownerType,
        @WebParam(name = "description", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String description);

    /**
     * 
     * @param groupName
     */
    @WebMethod(operationName = "RemoveGroup", action = "http://schemas.microsoft.com/sharepoint/soap/directory/RemoveGroup")
    @RequestWrapper(localName = "RemoveGroup", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveGroup")
    @ResponseWrapper(localName = "RemoveGroupResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveGroupResponse")
    public void removeGroup(
        @WebParam(name = "groupName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String groupName);

    /**
     * 
     * @param groupName
     * @param roleName
     */
    @WebMethod(operationName = "RemoveGroupFromRole", action = "http://schemas.microsoft.com/sharepoint/soap/directory/RemoveGroupFromRole")
    @RequestWrapper(localName = "RemoveGroupFromRole", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveGroupFromRole")
    @ResponseWrapper(localName = "RemoveGroupFromRoleResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveGroupFromRoleResponse")
    public void removeGroupFromRole(
        @WebParam(name = "roleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String roleName,
        @WebParam(name = "groupName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String groupName);

    /**
     * 
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetRoleCollectionFromWebResponse.GetRoleCollectionFromWebResult
     */
    @WebMethod(operationName = "GetRoleCollectionFromWeb", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetRoleCollectionFromWeb")
    @WebResult(name = "GetRoleCollectionFromWebResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetRoleCollectionFromWeb", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetRoleCollectionFromWeb")
    @ResponseWrapper(localName = "GetRoleCollectionFromWebResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetRoleCollectionFromWebResponse")
    public com.microsoft.schemas.sharepoint.soap.GetRoleCollectionFromWebResponse.GetRoleCollectionFromWebResult getRoleCollectionFromWeb();

    /**
     * 
     * @param groupName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetRoleCollectionFromGroupResponse.GetRoleCollectionFromGroupResult
     */
    @WebMethod(operationName = "GetRoleCollectionFromGroup", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetRoleCollectionFromGroup")
    @WebResult(name = "GetRoleCollectionFromGroupResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetRoleCollectionFromGroup", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetRoleCollectionFromGroup")
    @ResponseWrapper(localName = "GetRoleCollectionFromGroupResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetRoleCollectionFromGroupResponse")
    public com.microsoft.schemas.sharepoint.soap.GetRoleCollectionFromGroupResponse.GetRoleCollectionFromGroupResult getRoleCollectionFromGroup(
        @WebParam(name = "groupName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String groupName);

    /**
     * 
     * @param userLoginName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetRoleCollectionFromUserResponse.GetRoleCollectionFromUserResult
     */
    @WebMethod(operationName = "GetRoleCollectionFromUser", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetRoleCollectionFromUser")
    @WebResult(name = "GetRoleCollectionFromUserResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetRoleCollectionFromUser", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetRoleCollectionFromUser")
    @ResponseWrapper(localName = "GetRoleCollectionFromUserResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetRoleCollectionFromUserResponse")
    public com.microsoft.schemas.sharepoint.soap.GetRoleCollectionFromUserResponse.GetRoleCollectionFromUserResult getRoleCollectionFromUser(
        @WebParam(name = "userLoginName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String userLoginName);

    /**
     * 
     * @param roleNamesXml
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetRoleCollectionResponse.GetRoleCollectionResult
     */
    @WebMethod(operationName = "GetRoleCollection", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetRoleCollection")
    @WebResult(name = "GetRoleCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetRoleCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetRoleCollection")
    @ResponseWrapper(localName = "GetRoleCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetRoleCollectionResponse")
    public com.microsoft.schemas.sharepoint.soap.GetRoleCollectionResponse.GetRoleCollectionResult getRoleCollection(
        @WebParam(name = "roleNamesXml", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        com.microsoft.schemas.sharepoint.soap.GetRoleCollection.RoleNamesXml roleNamesXml);

    /**
     * 
     * @param roleName
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetRoleInfoResponse.GetRoleInfoResult
     */
    @WebMethod(operationName = "GetRoleInfo", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetRoleInfo")
    @WebResult(name = "GetRoleInfoResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetRoleInfo", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetRoleInfo")
    @ResponseWrapper(localName = "GetRoleInfoResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetRoleInfoResponse")
    public com.microsoft.schemas.sharepoint.soap.GetRoleInfoResponse.GetRoleInfoResult getRoleInfo(
        @WebParam(name = "roleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String roleName);

    /**
     * 
     * @param description
     * @param permissionMask
     * @param roleName
     */
    @WebMethod(operationName = "AddRole", action = "http://schemas.microsoft.com/sharepoint/soap/directory/AddRole")
    @RequestWrapper(localName = "AddRole", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddRole")
    @ResponseWrapper(localName = "AddRoleResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddRoleResponse")
    public void addRole(
        @WebParam(name = "roleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String roleName,
        @WebParam(name = "description", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String description,
        @WebParam(name = "permissionMask", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        int permissionMask);

    /**
     * 
     * @param description
     * @param permissionMask
     * @param roleName
     */
    @WebMethod(operationName = "AddRoleDef", action = "http://schemas.microsoft.com/sharepoint/soap/directory/AddRoleDef")
    @RequestWrapper(localName = "AddRoleDef", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddRoleDef")
    @ResponseWrapper(localName = "AddRoleDefResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.AddRoleDefResponse")
    public void addRoleDef(
        @WebParam(name = "roleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String roleName,
        @WebParam(name = "description", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String description,
        @WebParam(name = "permissionMask", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        BigInteger permissionMask);

    /**
     * 
     * @param oldRoleName
     * @param description
     * @param permissionMask
     * @param roleName
     */
    @WebMethod(operationName = "UpdateRoleInfo", action = "http://schemas.microsoft.com/sharepoint/soap/directory/UpdateRoleInfo")
    @RequestWrapper(localName = "UpdateRoleInfo", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.UpdateRoleInfo")
    @ResponseWrapper(localName = "UpdateRoleInfoResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.UpdateRoleInfoResponse")
    public void updateRoleInfo(
        @WebParam(name = "oldRoleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String oldRoleName,
        @WebParam(name = "roleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String roleName,
        @WebParam(name = "description", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String description,
        @WebParam(name = "permissionMask", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        int permissionMask);

    /**
     * 
     * @param oldRoleName
     * @param description
     * @param permissionMask
     * @param roleName
     */
    @WebMethod(operationName = "UpdateRoleDefInfo", action = "http://schemas.microsoft.com/sharepoint/soap/directory/UpdateRoleDefInfo")
    @RequestWrapper(localName = "UpdateRoleDefInfo", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.UpdateRoleDefInfo")
    @ResponseWrapper(localName = "UpdateRoleDefInfoResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.UpdateRoleDefInfoResponse")
    public void updateRoleDefInfo(
        @WebParam(name = "oldRoleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String oldRoleName,
        @WebParam(name = "roleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String roleName,
        @WebParam(name = "description", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String description,
        @WebParam(name = "permissionMask", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        BigInteger permissionMask);

    /**
     * 
     * @param roleName
     */
    @WebMethod(operationName = "RemoveRole", action = "http://schemas.microsoft.com/sharepoint/soap/directory/RemoveRole")
    @RequestWrapper(localName = "RemoveRole", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveRole")
    @ResponseWrapper(localName = "RemoveRoleResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.RemoveRoleResponse")
    public void removeRole(
        @WebParam(name = "roleName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        String roleName);

    /**
     * 
     * @param emailXml
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetUserLoginFromEmailResponse.GetUserLoginFromEmailResult
     */
    @WebMethod(operationName = "GetUserLoginFromEmail", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetUserLoginFromEmail")
    @WebResult(name = "GetUserLoginFromEmailResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetUserLoginFromEmail", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetUserLoginFromEmail")
    @ResponseWrapper(localName = "GetUserLoginFromEmailResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetUserLoginFromEmailResponse")
    public com.microsoft.schemas.sharepoint.soap.GetUserLoginFromEmailResponse.GetUserLoginFromEmailResult getUserLoginFromEmail(
        @WebParam(name = "emailXml", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
        com.microsoft.schemas.sharepoint.soap.GetUserLoginFromEmail.EmailXml emailXml);

    /**
     * 
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetRolesAndPermissionsForCurrentUserResponse.GetRolesAndPermissionsForCurrentUserResult
     */
    @WebMethod(operationName = "GetRolesAndPermissionsForCurrentUser", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetRolesAndPermissionsForCurrentUser")
    @WebResult(name = "GetRolesAndPermissionsForCurrentUserResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetRolesAndPermissionsForCurrentUser", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetRolesAndPermissionsForCurrentUser")
    @ResponseWrapper(localName = "GetRolesAndPermissionsForCurrentUserResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetRolesAndPermissionsForCurrentUserResponse")
    public com.microsoft.schemas.sharepoint.soap.GetRolesAndPermissionsForCurrentUserResponse.GetRolesAndPermissionsForCurrentUserResult getRolesAndPermissionsForCurrentUser();

    /**
     * 
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetRolesAndPermissionsForSiteResponse.GetRolesAndPermissionsForSiteResult
     */
    @WebMethod(operationName = "GetRolesAndPermissionsForSite", action = "http://schemas.microsoft.com/sharepoint/soap/directory/GetRolesAndPermissionsForSite")
    @WebResult(name = "GetRolesAndPermissionsForSiteResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/")
    @RequestWrapper(localName = "GetRolesAndPermissionsForSite", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetRolesAndPermissionsForSite")
    @ResponseWrapper(localName = "GetRolesAndPermissionsForSiteResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/directory/", className = "com.microsoft.schemas.sharepoint.soap.GetRolesAndPermissionsForSiteResponse")
    public com.microsoft.schemas.sharepoint.soap.GetRolesAndPermissionsForSiteResponse.GetRolesAndPermissionsForSiteResult getRolesAndPermissionsForSite();

}
