
package com.microsoft.schemas.sharepoint.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebPartPagesWebServiceSoap", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebPartPagesWebServiceSoap {


    /**
     * 
     * @param documentName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetWebPartPageDocument", action = "http://microsoft.com/sharepoint/webpartpages/GetWebPartPageDocument")
    @WebResult(name = "GetWebPartPageDocumentResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetWebPartPageDocument", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPartPageDocument")
    @ResponseWrapper(localName = "GetWebPartPageDocumentResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPartPageDocumentResponse")
    public String getWebPartPageDocument(
        @WebParam(name = "documentName", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String documentName);

    /**
     * 
     * @param behavior
     * @param documentName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetWebPartPage", action = "http://microsoft.com/sharepoint/webpartpages/GetWebPartPage")
    @WebResult(name = "GetWebPartPageResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetWebPartPage", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPartPage")
    @ResponseWrapper(localName = "GetWebPartPageResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPartPageResponse")
    public String getWebPartPage(
        @WebParam(name = "documentName", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String documentName,
        @WebParam(name = "behavior", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        SPWebServiceBehavior behavior);

    /**
     * 
     * @param webPartXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RenderWebPartForEdit", action = "http://microsoft.com/sharepoint/webpartpages/RenderWebPartForEdit")
    @WebResult(name = "RenderWebPartForEditResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "RenderWebPartForEdit", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.RenderWebPartForEdit")
    @ResponseWrapper(localName = "RenderWebPartForEditResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.RenderWebPartForEditResponse")
    public String renderWebPartForEdit(
        @WebParam(name = "webPartXml", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String webPartXml);

    /**
     * 
     * @param queryXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetXmlDataFromDataSource", action = "http://microsoft.com/sharepoint/webpartpages/GetXmlDataFromDataSource")
    @WebResult(name = "GetXmlDataFromDataSourceResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetXmlDataFromDataSource", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetXmlDataFromDataSource")
    @ResponseWrapper(localName = "GetXmlDataFromDataSourceResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetXmlDataFromDataSourceResponse")
    public String getXmlDataFromDataSource(
        @WebParam(name = "queryXml", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String queryXml);

    /**
     * 
     * @param dscXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFormCapabilityFromDataSourceControl", action = "http://microsoft.com/sharepoint/webpartpages/GetFormCapabilityFromDataSourceControl")
    @WebResult(name = "GetFormCapabilityFromDataSourceControlResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetFormCapabilityFromDataSourceControl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetFormCapabilityFromDataSourceControl")
    @ResponseWrapper(localName = "GetFormCapabilityFromDataSourceControlResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetFormCapabilityFromDataSourceControlResponse")
    public String getFormCapabilityFromDataSourceControl(
        @WebParam(name = "dscXml", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String dscXml);

    /**
     * 
     * @param contextUrl
     * @param dscXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDataFromDataSourceControl", action = "http://microsoft.com/sharepoint/webpartpages/GetDataFromDataSourceControl")
    @WebResult(name = "GetDataFromDataSourceControlResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetDataFromDataSourceControl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetDataFromDataSourceControl")
    @ResponseWrapper(localName = "GetDataFromDataSourceControlResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetDataFromDataSourceControlResponse")
    public String getDataFromDataSourceControl(
        @WebParam(name = "dscXml", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String dscXml,
        @WebParam(name = "contextUrl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String contextUrl);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FetchLegalWorkflowActions", action = "http://microsoft.com/sharepoint/webpartpages/FetchLegalWorkflowActions")
    @WebResult(name = "FetchLegalWorkflowActionsResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "FetchLegalWorkflowActions", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.FetchLegalWorkflowActions")
    @ResponseWrapper(localName = "FetchLegalWorkflowActionsResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.FetchLegalWorkflowActionsResponse")
    public String fetchLegalWorkflowActions();

    /**
     * 
     * @param flag
     * @param workflowMarkupText
     * @param configBlob
     * @param rulesText
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidateWorkflowMarkupAndCreateSupportObjects", action = "http://microsoft.com/sharepoint/webpartpages/ValidateWorkflowMarkupAndCreateSupportObjects")
    @WebResult(name = "ValidateWorkflowMarkupAndCreateSupportObjectsResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "ValidateWorkflowMarkupAndCreateSupportObjects", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.ValidateWorkflowMarkupAndCreateSupportObjects")
    @ResponseWrapper(localName = "ValidateWorkflowMarkupAndCreateSupportObjectsResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.ValidateWorkflowMarkupAndCreateSupportObjectsResponse")
    public String validateWorkflowMarkupAndCreateSupportObjects(
        @WebParam(name = "workflowMarkupText", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String workflowMarkupText,
        @WebParam(name = "rulesText", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String rulesText,
        @WebParam(name = "configBlob", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String configBlob,
        @WebParam(name = "flag", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String flag);

    /**
     * 
     * @param configVersion
     * @param configUrl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AssociateWorkflowMarkup", action = "http://microsoft.com/sharepoint/webpartpages/AssociateWorkflowMarkup")
    @WebResult(name = "AssociateWorkflowMarkupResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "AssociateWorkflowMarkup", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.AssociateWorkflowMarkup")
    @ResponseWrapper(localName = "AssociateWorkflowMarkupResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.AssociateWorkflowMarkupResponse")
    public String associateWorkflowMarkup(
        @WebParam(name = "configUrl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String configUrl,
        @WebParam(name = "configVersion", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String configVersion);

    /**
     * 
     * @param configVersion
     * @param configUrl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RemoveWorkflowAssociation", action = "http://microsoft.com/sharepoint/webpartpages/RemoveWorkflowAssociation")
    @WebResult(name = "RemoveWorkflowAssociationResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "RemoveWorkflowAssociation", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.RemoveWorkflowAssociation")
    @ResponseWrapper(localName = "RemoveWorkflowAssociationResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.RemoveWorkflowAssociationResponse")
    public String removeWorkflowAssociation(
        @WebParam(name = "configUrl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String configUrl,
        @WebParam(name = "configVersion", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String configVersion);

    /**
     * 
     * @param inputFormat
     * @param formatConversionOption
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConvertWebPartFormat", action = "http://microsoft.com/sharepoint/webpartpages/ConvertWebPartFormat")
    @WebResult(name = "ConvertWebPartFormatResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "ConvertWebPartFormat", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.ConvertWebPartFormat")
    @ResponseWrapper(localName = "ConvertWebPartFormatResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.ConvertWebPartFormatResponse")
    public String convertWebPartFormat(
        @WebParam(name = "inputFormat", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String inputFormat,
        @WebParam(name = "formatConversionOption", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        FormatConversionOption formatConversionOption);

    /**
     * 
     * @param baseTypes
     * @param assemblyName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAssemblyMetaData", action = "http://microsoft.com/sharepoint/webpartpages/GetAssemblyMetaData")
    @WebResult(name = "GetAssemblyMetaDataResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetAssemblyMetaData", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetAssemblyMetaData")
    @ResponseWrapper(localName = "GetAssemblyMetaDataResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetAssemblyMetaDataResponse")
    public String getAssemblyMetaData(
        @WebParam(name = "assemblyName", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String assemblyName,
        @WebParam(name = "baseTypes", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String baseTypes);

    /**
     * 
     * @param resourceName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBindingResourceData", action = "http://microsoft.com/sharepoint/webpartpages/GetBindingResourceData")
    @WebResult(name = "GetBindingResourceDataResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetBindingResourceData", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetBindingResourceData")
    @ResponseWrapper(localName = "GetBindingResourceDataResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetBindingResourceDataResponse")
    public String getBindingResourceData(
        @WebParam(name = "ResourceName", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String resourceName);

    /**
     * 
     * @param updateData
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ExecuteProxyUpdates", action = "http://microsoft.com/sharepoint/webpartpages/ExecuteProxyUpdates")
    @WebResult(name = "ExecuteProxyUpdatesResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "ExecuteProxyUpdates", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.ExecuteProxyUpdates")
    @ResponseWrapper(localName = "ExecuteProxyUpdatesResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.ExecuteProxyUpdatesResponse")
    public String executeProxyUpdates(
        @WebParam(name = "updateData", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String updateData);

    /**
     * 
     * @param pageUrl
     * @param zoneIndex
     * @param webPartXml
     * @param zoneId
     * @param storage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddWebPartToZone", action = "http://microsoft.com/sharepoint/webpartpages/AddWebPartToZone")
    @WebResult(name = "AddWebPartToZoneResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "AddWebPartToZone", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.AddWebPartToZone")
    @ResponseWrapper(localName = "AddWebPartToZoneResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.AddWebPartToZoneResponse")
    public String addWebPartToZone(
        @WebParam(name = "pageUrl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String pageUrl,
        @WebParam(name = "webPartXml", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String webPartXml,
        @WebParam(name = "storage", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        Storage storage,
        @WebParam(name = "zoneId", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String zoneId,
        @WebParam(name = "zoneIndex", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        int zoneIndex);

    /**
     * 
     * @param pageUrl
     * @param webPartXml
     * @param storage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddWebPart", action = "http://microsoft.com/sharepoint/webpartpages/AddWebPart")
    @WebResult(name = "AddWebPartResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "AddWebPart", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.AddWebPart")
    @ResponseWrapper(localName = "AddWebPartResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.AddWebPartResponse")
    public String addWebPart(
        @WebParam(name = "pageUrl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String pageUrl,
        @WebParam(name = "webPartXml", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String webPartXml,
        @WebParam(name = "storage", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        Storage storage);

    /**
     * 
     * @param pageurl
     * @param storage
     * @param storageKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetWebPart", action = "http://microsoft.com/sharepoint/webpartpages/GetWebPart")
    @WebResult(name = "GetWebPartResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetWebPart", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPart")
    @ResponseWrapper(localName = "GetWebPartResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPartResponse")
    public String getWebPart(
        @WebParam(name = "pageurl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String pageurl,
        @WebParam(name = "storageKey", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String storageKey,
        @WebParam(name = "storage", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        Storage storage);

    /**
     * 
     * @param pageurl
     * @param behavior
     * @param storage
     * @param storageKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetWebPart2", action = "http://microsoft.com/sharepoint/webpartpages/GetWebPart2")
    @WebResult(name = "GetWebPart2Result", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetWebPart2", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPart2")
    @ResponseWrapper(localName = "GetWebPart2Response", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPart2Response")
    public String getWebPart2(
        @WebParam(name = "pageurl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String pageurl,
        @WebParam(name = "storageKey", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String storageKey,
        @WebParam(name = "storage", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        Storage storage,
        @WebParam(name = "behavior", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        SPWebServiceBehavior behavior);

    /**
     * 
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetCustomControlListResponse.GetCustomControlListResult
     */
    @WebMethod(operationName = "GetCustomControlList", action = "http://microsoft.com/sharepoint/webpartpages/GetCustomControlList")
    @WebResult(name = "GetCustomControlListResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetCustomControlList", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetCustomControlList")
    @ResponseWrapper(localName = "GetCustomControlListResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetCustomControlListResponse")
    public com.microsoft.schemas.sharepoint.soap.GetCustomControlListResponse.GetCustomControlListResult getCustomControlList();

    /**
     * 
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetSafeAssemblyInfoResponse.GetSafeAssemblyInfoResult
     */
    @WebMethod(operationName = "GetSafeAssemblyInfo", action = "http://microsoft.com/sharepoint/webpartpages/GetSafeAssemblyInfo")
    @WebResult(name = "GetSafeAssemblyInfoResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetSafeAssemblyInfo", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetSafeAssemblyInfo")
    @ResponseWrapper(localName = "GetSafeAssemblyInfoResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetSafeAssemblyInfoResponse")
    public com.microsoft.schemas.sharepoint.soap.GetSafeAssemblyInfoResponse.GetSafeAssemblyInfoResult getSafeAssemblyInfo();

    /**
     * 
     * @param pageUrl
     * @param storage
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetWebPartPropertiesResponse.GetWebPartPropertiesResult
     */
    @WebMethod(operationName = "GetWebPartProperties", action = "http://microsoft.com/sharepoint/webpartpages/GetWebPartProperties")
    @WebResult(name = "GetWebPartPropertiesResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetWebPartProperties", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPartProperties")
    @ResponseWrapper(localName = "GetWebPartPropertiesResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPartPropertiesResponse")
    public com.microsoft.schemas.sharepoint.soap.GetWebPartPropertiesResponse.GetWebPartPropertiesResult getWebPartProperties(
        @WebParam(name = "pageUrl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String pageUrl,
        @WebParam(name = "storage", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        Storage storage);

    /**
     * 
     * @param behavior
     * @param pageUrl
     * @param storage
     * @return
     *     returns com.microsoft.schemas.sharepoint.soap.GetWebPartProperties2Response.GetWebPartProperties2Result
     */
    @WebMethod(operationName = "GetWebPartProperties2", action = "http://microsoft.com/sharepoint/webpartpages/GetWebPartProperties2")
    @WebResult(name = "GetWebPartProperties2Result", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetWebPartProperties2", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPartProperties2")
    @ResponseWrapper(localName = "GetWebPartProperties2Response", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPartProperties2Response")
    public com.microsoft.schemas.sharepoint.soap.GetWebPartProperties2Response.GetWebPartProperties2Result getWebPartProperties2(
        @WebParam(name = "pageUrl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String pageUrl,
        @WebParam(name = "storage", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        Storage storage,
        @WebParam(name = "behavior", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        SPWebServiceBehavior behavior);

    /**
     * 
     * @param pageUrl
     * @param webPartXml
     * @param storage
     * @param storageKey
     */
    @WebMethod(operationName = "SaveWebPart", action = "http://microsoft.com/sharepoint/webpartpages/SaveWebPart")
    @RequestWrapper(localName = "SaveWebPart", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.SaveWebPart")
    @ResponseWrapper(localName = "SaveWebPartResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.SaveWebPartResponse")
    public void saveWebPart(
        @WebParam(name = "pageUrl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String pageUrl,
        @WebParam(name = "storageKey", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String storageKey,
        @WebParam(name = "webPartXml", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String webPartXml,
        @WebParam(name = "storage", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        Storage storage);

    /**
     * 
     * @param pageUrl
     * @param allowTypeChange
     * @param webPartXml
     * @param storage
     * @param storageKey
     */
    @WebMethod(operationName = "SaveWebPart2", action = "http://microsoft.com/sharepoint/webpartpages/SaveWebPart2")
    @RequestWrapper(localName = "SaveWebPart2", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.SaveWebPart2")
    @ResponseWrapper(localName = "SaveWebPart2Response", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.SaveWebPart2Response")
    public void saveWebPart2(
        @WebParam(name = "pageUrl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String pageUrl,
        @WebParam(name = "storageKey", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String storageKey,
        @WebParam(name = "webPartXml", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String webPartXml,
        @WebParam(name = "storage", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        Storage storage,
        @WebParam(name = "allowTypeChange", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        boolean allowTypeChange);

    /**
     * 
     * @param pageUrl
     * @param storage
     * @param storageKey
     */
    @WebMethod(operationName = "DeleteWebPart", action = "http://microsoft.com/sharepoint/webpartpages/DeleteWebPart")
    @RequestWrapper(localName = "DeleteWebPart", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.DeleteWebPart")
    @ResponseWrapper(localName = "DeleteWebPartResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.DeleteWebPartResponse")
    public void deleteWebPart(
        @WebParam(name = "pageUrl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String pageUrl,
        @WebParam(name = "storageKey", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String storageKey,
        @WebParam(name = "storage", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        Storage storage);

    /**
     * 
     * @param lcid
     * @param sourcePageContents
     * @param sourcePageUrl
     * @param providerPartID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetWebPartPageConnectionInfo", action = "http://microsoft.com/sharepoint/webpartpages/GetWebPartPageConnectionInfo")
    @WebResult(name = "GetWebPartPageConnectionInfoResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetWebPartPageConnectionInfo", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPartPageConnectionInfo")
    @ResponseWrapper(localName = "GetWebPartPageConnectionInfoResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPartPageConnectionInfoResponse")
    public String getWebPartPageConnectionInfo(
        @WebParam(name = "sourcePageUrl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String sourcePageUrl,
        @WebParam(name = "sourcePageContents", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String sourcePageContents,
        @WebParam(name = "providerPartID", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String providerPartID,
        @WebParam(name = "lcid", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String lcid);

    /**
     * 
     * @param lcid
     * @param sourcePageContents
     * @param sourcePageUrl
     * @param providerPartID
     * @param targetPageContents
     * @param targetPageUrl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetWebPartCrossPageCompatibility", action = "http://microsoft.com/sharepoint/webpartpages/GetWebPartCrossPageCompatibility")
    @WebResult(name = "GetWebPartCrossPageCompatibilityResult", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
    @RequestWrapper(localName = "GetWebPartCrossPageCompatibility", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPartCrossPageCompatibility")
    @ResponseWrapper(localName = "GetWebPartCrossPageCompatibilityResponse", targetNamespace = "http://microsoft.com/sharepoint/webpartpages", className = "com.microsoft.schemas.sharepoint.soap.GetWebPartCrossPageCompatibilityResponse")
    public String getWebPartCrossPageCompatibility(
        @WebParam(name = "sourcePageUrl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String sourcePageUrl,
        @WebParam(name = "sourcePageContents", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String sourcePageContents,
        @WebParam(name = "targetPageUrl", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String targetPageUrl,
        @WebParam(name = "targetPageContents", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String targetPageContents,
        @WebParam(name = "providerPartID", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String providerPartID,
        @WebParam(name = "lcid", targetNamespace = "http://microsoft.com/sharepoint/webpartpages")
        String lcid);

}
